from __future__ import annotations

import hashlib
import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .errors import VeritasFailure
from .planning import PlanningEvidence, build_evidence_backed_plan


def _safe_name(text: str) -> str:
    cleaned = "".join(ch.lower() if ch.isalnum() else "_" for ch in text)
    return "_".join(part for part in cleaned.split("_") if part)[:80] or "veritas_generated"


def _output_root(cfg: dict[str, Any]) -> Path:
    return Path(cfg.get("codegen", {}).get("package_outputs_dir", "/workspace/data/generated"))


def _language_files(language: str, package_name: str, prompt: str) -> dict[str, str]:
    lang = language.lower()
    if lang == "python":
        return {
            "pyproject.toml": f"""[project]\nname = \"{package_name}\"\nversion = \"0.1.0\"\ndescription = \"Veritas generated evidence-backed research package\"\nrequires-python = \">=3.11\"\ndependencies = [\"numpy>=1.26\"]\n\n[tool.pytest.ini_options]\ntestpaths = [\"tests\"]\n""",
            f"src/{package_name}/__init__.py": f"""\"\"\"Veritas generated package.\n\nPrompt: {prompt}\n\nThis package is generated as an evidence-backed starting point. Review the\nvalidation report before using it in production.\n\"\"\"\n\nfrom .core import describe_model\n\n__all__ = [\"describe_model\"]\n""",
            f"src/{package_name}/core.py": """from __future__ import annotations\n\n\ndef describe_model() -> dict[str, object]:\n    \"\"\"Return package metadata generated by Veritas.\n\n    Acceptance criteria:\n        1. Deterministic: same package returns the same metadata.\n        2. Auditable: reports that implementation must be reviewed.\n        3. Safe default: does not claim theorem-level correctness.\n    \"\"\"\n\n    return {\n        \"status\": \"generated_scaffold_requires_review\",\n        \"backend\": \"cpu\",\n    }\n""",
            "tests/test_core.py": f"""from {package_name}.core import describe_model\n\n\ndef test_describe_model_status():\n    assert describe_model()[\"status\"] == \"generated_scaffold_requires_review\"\n""",
        }
    if lang in {"rust", "cuda", "cpp"}:
        cargo_toml = f"""[package]\nname = \"{package_name}\"\nversion = \"0.1.0\"\nedition = \"2021\"\nlicense = \"Apache-2.0\"\n\n[features]\ndefault = [\"cpu\"]\ncpu = []\ncuda = []\n\n[lib]\npath = \"src/lib.rs\"\n"""
        lib_rs = f"""//! Veritas generated evidence-backed package.\n//!\n//! Prompt: {prompt}\n//!\n//! This is a production package scaffold with explicit validation gates.\n//! Replace the generated implementation only after reviewing evidence,\n//! assumptions, invariants, and tests in `VALIDATION_REPORT.md`.\n\n/// Return generated package status.\npub fn describe_model() -> &'static str {{\n    \"generated_scaffold_requires_review\"\n}}\n\n#[cfg(test)]\nmod tests {{\n    use super::*;\n\n    #[test]\n    fn status_is_explicitly_review_gated() {{\n        assert_eq!(describe_model(), \"generated_scaffold_requires_review\");\n    }}\n}}\n"""
        return {"Cargo.toml": cargo_toml, "src/lib.rs": lib_rs}
    raise VeritasFailure(
        stage="codegen.language",
        message=f"Unsupported language: {language}",
        remediation="Use one of: rust, python, cuda, cpp. Update config/codegen.allowed_languages before adding a new backend.",
    )


def _markdown_list(items: list[Any]) -> str:
    if not items:
        return "- None recorded.\n"
    return "".join(f"- {str(item)}\n" for item in items)


def _evidence_summary(plan: dict[str, Any]) -> str:
    evidence = plan.get("evidence", {})
    hits = evidence.get("opensearch_hits", [])[:8]
    formulas = evidence.get("formula_bindings", [])[:12]
    lines = ["# Evidence Summary\n"]
    lines.append("## OpenSearch FAISS/HNSW evidence\n")
    for hit in hits:
        lines.append(f"- `{hit.get('chunk_id')}` score={hit.get('score')} title={hit.get('title')}\n")
    lines.append("\n## Formula symbolic shadows\n")
    for row in formulas:
        expr = str(row.get("expr", "")).replace("\n", " ")[:300]
        lines.append(f"- `{expr}`\n")
    return "".join(lines)


def generate_package(prompt: str, language: str, cfg: dict[str, Any]) -> dict[str, Any]:
    """Generate an evidence-backed distributable package scaffold.

    Acceptance criteria:
        1. Gather evidence before creating files.
        2. Write a package directory with source, tests, README, manifest, and validation report.
        3. Clearly mark generated code as review-gated instead of falsely production-certified.
        4. Preserve evidence references and formulas in generated documentation.
    """

    plan = build_evidence_backed_plan(prompt, cfg, size=int(cfg.get("retrieval", {}).get("top_k", 8)))
    digest = hashlib.sha256(prompt.encode("utf-8")).hexdigest()[:10]
    package_name = f"veritas_{_safe_name(prompt)}_{digest}".replace("-", "_")
    output_dir = _output_root(cfg) / package_name
    output_dir.mkdir(parents=True, exist_ok=True)
    files = _language_files(language, package_name, prompt)
    for relative, content in files.items():
        target = output_dir / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")

    analysis = plan.get("analysis", {})
    readme = f"""# {package_name}\n\nGenerated by **Veritas** from evidence-backed mathematical research context.\n\n## Prompt\n\n```text\n{prompt}\n```\n\n## Status\n\nThis package is a **review-gated production scaffold**. It contains source, tests,\nand validation artifacts, but it is not theorem-certified until the validation\ngates in `VALIDATION_REPORT.md` pass.\n\n## Representation-first analysis\n\n- Surface phenomenon: {analysis.get('surface_phenomenon', {}).get('apparent_complexity', [])}\n- Candidate representation map: {analysis.get('representation_hypothesis', {}).get('candidate_map')}\n- Candidate invariants:\n{_markdown_list(analysis.get('candidate_invariants', []))}\n## Build / test\n\nSee language-specific package files.\n"""
    (output_dir / "README.md").write_text(readme, encoding="utf-8")
    validation_report = f"""# Veritas Validation Report\n\nGenerated: {datetime.now(timezone.utc).isoformat()}\n\n## Required gates\n\n{_markdown_list(analysis.get('validation_gates', []))}\n## Risks\n\n{_markdown_list([json.dumps(risk, ensure_ascii=False) for risk in analysis.get('risk_register', [])])}\n## Compression fidelity gates\n\n{_markdown_list(analysis.get('compression_fidelity_gates', []))}\n## Warnings\n\n{_markdown_list([json.dumps(w, ensure_ascii=False) for w in plan.get('evidence', {}).get('warnings', [])])}\n## Status\n\n`generated_scaffold_requires_review`\n"""
    (output_dir / "VALIDATION_REPORT.md").write_text(validation_report, encoding="utf-8")
    (output_dir / "EVIDENCE.md").write_text(_evidence_summary(plan), encoding="utf-8")
    manifest = {
        "ok": True,
        "package_name": package_name,
        "language": language,
        "prompt": prompt,
        "path": str(output_dir),
        "status": "generated_scaffold_requires_review",
        "plan": plan,
    }
    (output_dir / "veritas_manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    return manifest
