from __future__ import annotations

import hashlib
import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import requests

from .errors import VeritasFailure

LEGACY_CODEGEN_WARNING = "Legacy Python scaffold generator: outputs are generated_unvalidated and must not be treated as production-ready."
from .planning import PlanningEvidence, build_evidence_backed_plan


def _safe_name(text: str) -> str:
    cleaned = "".join(ch.lower() if ch.isalnum() else "_" for ch in text)
    return "_".join(part for part in cleaned.split("_") if part)[:80] or "veritas_generated"


def _output_root(cfg: dict[str, Any]) -> Path:
    return Path(cfg.get("codegen", {}).get("package_outputs_dir", "/workspace/data/generated"))


def _language_files(language: str, package_name: str, prompt: str) -> dict[str, str]:
    lang = language.lower()
    if lang == "python":
        return {
            "pyproject.toml": f"""[project]\nname = \"{package_name}\"\nversion = \"0.1.0\"\ndescription = \"Veritas generated evidence-backed research package\"\nrequires-python = \">=3.11\"\ndependencies = [\"numpy>=1.26\"]\n\n[tool.pytest.ini_options]\ntestpaths = [\"tests\"]\n""",
            f"src/{package_name}/__init__.py": f"""\"\"\"Veritas generated package.\n\nPrompt: {prompt}\n\nThis package is generated as an evidence-backed starting point. Review the\nvalidation report before using it in production.\n\"\"\"\n\nfrom .core import describe_model\n\n__all__ = [\"describe_model\"]\n""",
            f"src/{package_name}/core.py": """from __future__ import annotations\n\n\ndef describe_model() -> dict[str, object]:\n    \"\"\"Return package metadata generated by Veritas.\n\n    Acceptance criteria:\n        1. Deterministic: same package returns the same metadata.\n        2. Auditable: reports that implementation must be validated.\n        3. Safe default: does not claim theorem-level correctness.\n    \"\"\"\n\n    return {\n        \"status\": \"generated_unvalidated\",\n        \"backend\": \"cpu\",\n    }\n""",
            "tests/test_core.py": f"""from {package_name}.core import describe_model\n\n\ndef test_describe_model_status():\n    assert describe_model()[\"status\"] == \"generated_unvalidated\"\n""",
        }
    if lang in {"rust", "cuda", "cpp"}:
        cargo_toml = f"""[package]\nname = \"{package_name}\"\nversion = \"0.1.0\"\nedition = \"2021\"\nlicense = \"Apache-2.0\"\n\n[features]\ndefault = [\"cpu\"]\ncpu = []\ncuda = []\n\n[lib]\npath = \"src/lib.rs\"\n"""
        lib_rs = f"""//! Veritas generated evidence-backed package.\n//!\n//! Prompt: {prompt}\n//!\n//! This is a validation-gated production candidate with explicit validation gates.\n//! Replace the generated implementation only after validateing evidence,\n//! assumptions, invariants, and tests in `VALIDATION_REPORT.md`.\n\n/// Return generated package status.\npub fn describe_model() -> &'static str {{\n    \"generated_unvalidated\"\n}}\n\n#[cfg(test)]\nmod tests {{\n    use super::*;\n\n    #[test]\n    fn status_is_explicitly_validate_gated() {{\n        assert_eq!(describe_model(), \"generated_unvalidated\");\n    }}\n}}\n"""
        return {"Cargo.toml": cargo_toml, "src/lib.rs": lib_rs}
    raise VeritasFailure(
        stage="codegen.language",
        message=f"Unsupported language: {language}",
        remediation="Use one of: rust, python, cuda, cpp. Update config/codegen.allowed_languages before adding a new backend.",
    )


def _markdown_list(items: list[Any]) -> str:
    if not items:
        return "- None recorded.\n"
    return "".join(f"- {str(item)}\n" for item in items)



def _model_cfg(cfg: dict[str, Any]) -> dict[str, Any]:
    return cfg.get("services", {}).get("model", {}).get("code", {})


def _vllm_url(cfg: dict[str, Any]) -> str:
    model_cfg = _model_cfg(cfg)
    env_name = model_cfg.get("url_env", "VERITAS_CODE_VLLM_URL")
    return os.getenv(env_name, model_cfg.get("default_url", "http://vllm-code:8000"))


def _vllm_served_model_name(cfg: dict[str, Any]) -> str:
    model_cfg = _model_cfg(cfg)
    env_name = model_cfg.get("served_model_name_env", "VERITAS_CODE_SERVED_MODEL_NAME")
    return os.getenv(env_name, model_cfg.get("default_served_model_name", "veritas-code"))


def _vllm_hf_model_id(cfg: dict[str, Any]) -> str:
    model_cfg = _model_cfg(cfg)
    env_name = model_cfg.get("model_env", "VERITAS_CODE_MODEL")
    return os.getenv(env_name, model_cfg.get("default_model", "Qwen/Qwen2.5-Coder-14B-Instruct"))


def _call_codegen_model(prompt: str, language: str, plan: dict[str, Any], cfg: dict[str, Any]) -> dict[str, Any]:
    """Call the configured vLLM code model and return generated text.

    Acceptance criteria:
        1. Use vLLM's OpenAI-compatible chat completions endpoint.
        2. Include evidence, formulas, risks, and validation gates in the prompt.
        3. Return structured warning data instead of failing package generation.
    """

    url = _vllm_url(cfg).rstrip("/") + "/v1/chat/completions"
    served_model = _vllm_served_model_name(cfg)
    hf_model = _vllm_hf_model_id(cfg)
    model_cfg = _model_cfg(cfg)
    system = (
        "You are Veritas Code Writer. Generate maintainable, testable, validation-gated "
        "production code from evidence-backed math research. Do not claim proof or "
        "production certification unless validation gates pass. Return concise file-oriented output."
    )
    user = json.dumps(
        {
            "language": language,
            "user_prompt": prompt,
            "requirements": [
                "cite evidence chunks and formulas",
                "state assumptions and invariants",
                "include tests and failure modes",
                "design CPU first with GPU extension points when relevant",
                "keep implementation maintainable for open-source contributors",
            ],
            "plan": plan,
        },
        ensure_ascii=False,
    )
    payload = {
        "model": served_model,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        "temperature": float(model_cfg.get("temperature", 0.05)),
        "max_tokens": int(model_cfg.get("max_tokens", 4096)),
    }
    try:
        response = requests.post(url, json=payload, timeout=900)
    except requests.RequestException as exc:
        return {
            "ok": False,
            "stage": "codegen.vllm_transport",
            "message": f"Code model request failed before response: {exc}",
            "remediation": "Start the code model with `docker compose --profile code-model up -d vllm-code`, or switch to a reachable vLLM endpoint.",
            "model": hf_model,
            "served_model": served_model,
            "url": url,
        }
    if response.status_code >= 400:
        return {
            "ok": False,
            "stage": "codegen.vllm_upstream",
            "message": f"Code model returned HTTP {response.status_code}: {response.text[:1200]}",
            "remediation": "Check Hugging Face model ID, HF_TOKEN, GPU memory, and `docker compose logs vllm-code`.",
            "model": hf_model,
            "served_model": served_model,
            "url": url,
        }
    try:
        payload = response.json()
    except ValueError:
        return {
            "ok": False,
            "stage": "codegen.vllm_parse",
            "message": "Code model returned non-JSON output from the OpenAI-compatible endpoint.",
            "remediation": "Verify the vLLM endpoint is /v1/chat/completions and not a raw text endpoint.",
            "raw": response.text[:2000],
            "model": hf_model,
        }
    content = (
        payload.get("choices", [{}])[0]
        .get("message", {})
        .get("content", "")
    )
    if not content.strip():
        return {
            "ok": False,
            "stage": "codegen.vllm_empty",
            "message": "Code model returned no content.",
            "remediation": "Retry with a more specific prompt or inspect vLLM logs.",
            "model": hf_model,
            "served_model": served_model,
            "response": payload,
        }
    return {
        "ok": True,
        "stage": "codegen.vllm_success",
        "model": hf_model,
        "served_model": served_model,
        "url": url,
        "content": content,
        "raw_response": payload,
    }


def _evidence_summary(plan: dict[str, Any]) -> str:
    evidence = plan.get("evidence", {})
    hits = evidence.get("opensearch_hits", [])[:8]
    formulas = evidence.get("formula_bindings", [])[:12]
    lines = ["# Evidence Summary\n"]
    lines.append("## OpenSearch FAISS/HNSW evidence\n")
    for hit in hits:
        lines.append(f"- `{hit.get('chunk_id')}` score={hit.get('score')} title={hit.get('title')}\n")
    lines.append("\n## Formula symbolic shadows\n")
    for row in formulas:
        expr = str(row.get("expr", "")).replace("\n", " ")[:300]
        lines.append(f"- `{expr}`\n")
    return "".join(lines)


def generate_package(prompt: str, language: str, cfg: dict[str, Any]) -> dict[str, Any]:
    """Generate an evidence-backed distributable package candidate.

    Acceptance criteria:
        1. Gather evidence before creating files.
        2. Write a package directory with source, tests, README, manifest, and validation report.
        3. Mark generated code as generated_unvalidated only after validation gates pass in the active run loop.
        4. Preserve evidence references and formulas in generated documentation.
    """

    plan = build_evidence_backed_plan(prompt, cfg, size=int(cfg.get("retrieval", {}).get("top_k", 8)))
    model_output = _call_codegen_model(prompt, language, plan, cfg)
    digest = hashlib.sha256(prompt.encode("utf-8")).hexdigest()[:10]
    package_name = f"veritas_{_safe_name(prompt)}_{digest}".replace("-", "_")
    output_dir = _output_root(cfg) / package_name
    output_dir.mkdir(parents=True, exist_ok=True)
    files = _language_files(language, package_name, prompt)
    for relative, content in files.items():
        target = output_dir / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")

    if model_output.get("ok"):
        (output_dir / "MODEL_OUTPUT.md").write_text(model_output.get("content", ""), encoding="utf-8")
    else:
        (output_dir / "MODEL_OUTPUT_ERROR.json").write_text(
            json.dumps(model_output, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )

    analysis = plan.get("analysis", {})
    readme = f"""# {package_name}\n\nGenerated by **Veritas** from evidence-backed mathematical research context.\n\n## Prompt\n\n```text\n{prompt}\n```\n\n## Status\n\nThis package is a **validation-gated production candidate**. It contains source, tests,\nand validation artifacts, but it is not theorem-certified until the validation\ngates in `VALIDATION_REPORT.md` pass.\n\n## Representation-first analysis\n\n- Surface phenomenon: {analysis.get('surface_phenomenon', {}).get('apparent_complexity', [])}\n- Candidate representation map: {analysis.get('representation_hypothesis', {}).get('candidate_map')}\n- Candidate invariants:\n{_markdown_list(analysis.get('candidate_invariants', []))}\n## Build / test\n\nSee language-specific package files.\n"""
    (output_dir / "README.md").write_text(readme, encoding="utf-8")
    validation_report = f"""# Veritas Validation Report\n\nGenerated: {datetime.now(timezone.utc).isoformat()}\n\n## Required gates\n\n{_markdown_list(analysis.get('validation_gates', []))}\n## Risks\n\n{_markdown_list([json.dumps(risk, ensure_ascii=False) for risk in analysis.get('risk_register', [])])}\n## Compression fidelity gates\n\n{_markdown_list(analysis.get('compression_fidelity_gates', []))}\n## Warnings\n\n{_markdown_list([json.dumps(w, ensure_ascii=False) for w in plan.get('evidence', {}).get('warnings', [])])}\n## Status\n\n`generated_unvalidated`\n"""
    (output_dir / "VALIDATION_REPORT.md").write_text(validation_report, encoding="utf-8")
    (output_dir / "EVIDENCE.md").write_text(_evidence_summary(plan), encoding="utf-8")
    manifest = {
        "ok": True,
        "package_name": package_name,
        "language": language,
        "prompt": prompt,
        "path": str(output_dir),
        "status": "generated_unvalidated",
        "plan": plan,
        "code_model_output": model_output,
    }
    (output_dir / "veritas_manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    return manifest
