use anyhow::{anyhow, Result};
use clap::{Parser, Subcommand};
use reqwest::Client;
use serde_json::{json, Value};
use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::process::Command;

const VERITAS_LOGO: &str = r#"
██╗   ██╗███████╗██████╗ ██╗████████╗ █████╗ ███████╗
██║   ██║██╔════╝██╔══██╗██║╚══██╔══╝██╔══██╗██╔════╝
██║   ██║█████╗  ██████╔╝██║   ██║   ███████║███████╗
╚██╗ ██╔╝██╔══╝  ██╔══██╗██║   ██║   ██╔══██║╚════██║
 ╚████╔╝ ███████╗██║  ██║██║   ██║   ██║  ██║███████║
  ╚═══╝  ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚═╝  ╚═╝╚══════╝
"#;

const MOTTO: &str = "Mathematical Truth Through Evidence";
const TAGLINE: &str =
    "Math-heavy evidence-backed research and development software engineering agent.";

const DEFAULT_PLANNER_MODEL: &str = "Qwen/Qwen2.5-Coder-7B-Instruct";
const DEFAULT_CODE_MODEL: &str = "Qwen/Qwen2.5-Coder-14B-Instruct";
const DEFAULT_CODE_FALLBACK_MODEL: &str = "deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct";
const DEFAULT_MATH_MODEL: &str = "allenai/Olmo-3-7B-Instruct";
const DEFAULT_MATH_LARGE_MODEL: &str = "allenai/Olmo-3.1-32B-Instruct";
const DEFAULT_EMBEDDING_MODEL: &str = "Muennighoff/SBERT-base-nli-v2";
const DEFAULT_VLLM_IMAGE: &str = "vllm/vllm-openai:latest";

#[derive(Parser)]
#[command(
    name = "veritas",
    version,
    about = "Veritas CLI: evidence-backed math research to production-grade code"
)]
struct Cli {
    #[arg(long, env = "VERITAS_API_URL", default_value = "http://localhost:8080")]
    api_url: String,
    #[command(subcommand)]
    command: Option<Commands>,
}


#[derive(Subcommand)]
enum JourneyCommands {
    /// Run the real Veritas journey orchestrator. This is the canonical end-user product path.
    Run {
        #[arg(long)]
        source: Option<PathBuf>,
        #[arg(long, default_value = "local")]
        mode: String,
        #[arg(long)]
        goal: Option<String>,
        #[arg(long, default_value = "rust")]
        language: String,
        #[arg(long, default_value = "require_high_risk_only")]
        policy: String,
        #[arg(long)]
        max_retries: Option<usize>,
    },
    /// Show status for a real Veritas journey run.
    Status { run_id: String },
    /// Record a human review decision for a journey checkpoint.
    Review {
        run_id: String,
        #[arg(long)]
        phase: String,
        #[arg(long)]
        decision: String,
        #[arg(long)]
        notes: Option<String>,
        #[arg(long, default_value = "human")]
        reviewer: String,
    },
    /// Resume an interrupted journey run.
    Resume { run_id: String },
    /// Fetch the journey report bundle.
    Report { run_id: String },
}

#[derive(Subcommand)]
enum Commands {
    /// Print the Veritas logo and guided workflow menu.
    Welcome,
    /// Create or update .veritas deployment config through an interactive setup/deployment wizard.
    Init,
    /// Alias for init.
    Configure,
    /// Validate generated setup/deployment config.
    SetupValidate,
    /// Deploy using .veritas/runtime.env generated by init.
    Deploy {
        #[arg(long, default_value_t = true)]
        models: bool,
    },
    /// Run the local fake-vLLM Docker Compose E2E proof path.
    E2eFake {
        #[arg(long, default_value_t = false)]
        keep_running: bool,
    },
    /// Run host validation: Python, Rust, Docker config, and fake-vLLM E2E.
    ValidateHost,
    /// Run the strict production acceptance gate.
    ProductionAccept {
        #[arg(long, default_value_t = false)]
        live_vllm: bool,
    },
    /// Enter guided prompting mode after deployment.
    Prompt,
    /// Real end-to-end Veritas journey workflow: source -> governed artifact.
    Journey {
        #[command(subcommand)]
        command: JourneyCommands,
    },
    /// Start the Docker Compose stack.
    Start {
        #[arg(long, default_value_t = false)]
        models: bool,
        #[arg(long, default_value_t = false)]
        code_model: bool,
        #[arg(long, default_value_t = false)]
        math_model: bool,
    },
    /// Start core services only.
    Up,
    /// Stop services.
    Down,
    /// API health check.
    Health,
    /// Full service readiness check.
    Ready,
    /// Show configured model roles and vLLM endpoints.
    Models,
    /// Inspect NVIDIA GPUs available to the host for vLLM role placement.
    GpuInspect,
    /// Validate GPU routing and tensor/pipeline parallel settings captured by setup.
    GpuValidate,
    /// Print the production OpenSearch mapping that Veritas expects.
    #[command(name = "opensearch-mapping", alias = "open-search-mapping")]
    OpenSearchMapping,
    /// Create or update the versioned OpenSearch FAISS/HNSW index and aliases.
    #[command(name = "opensearch-migrate", alias = "open-search-migrate")]
    OpenSearchMigrate {
        #[arg(long, default_value_t = false)]
        dry_run: bool,
    },
    /// Show OpenSearch versioned index and alias status.
    #[command(name = "opensearch-status", alias = "open-search-status")]
    OpenSearchStatus,
    /// List configured and discovered Fuseki named graphs.
    GraphList,
    /// Summarize ontology-derived planner facts from the SPARQL query pack.
    GraphFacts,
    /// Count triples in a Fuseki named graph.
    GraphDescribe { graph_uri: String },
    /// Upload local Turtle RDF into a named Fuseki graph.
    GraphUpload {
        #[arg(long)]
        path: PathBuf,
        #[arg(long)]
        graph_uri: String,
        #[arg(long, default_value_t = false)]
        replace: bool,
    },
    /// Convert a formula or math problem into validated code through the math-to-code workflow.
    MathToCode {
        #[arg(long)]
        formula_id: Option<String>,
        #[arg(long)]
        formula_record_id: Option<String>,
        #[arg(long)]
        citation_record_id: Option<String>,
        #[arg(long)]
        evidence_manifest_path: Option<PathBuf>,
        #[arg(long)]
        formula_latex: Option<String>,
        #[arg(long)]
        prompt: Option<String>,
        #[arg(long, default_value = "rust")]
        language: String,
        #[arg(long)]
        max_retries: Option<usize>,
        #[arg(long, default_value_t = false)]
        allow_exploratory_unverified: bool,
    },
    /// Inspect a local Evidence Eligibility Registry from a journey/ingestion workspace.
    EvidenceRegistryStatus {
        #[arg(long)]
        path: PathBuf,
    },
    /// Inspect a persisted run by id.
    RunStatus { run_id: String },
    /// Request cancellation of a persisted run.
    RunCancel { run_id: String },
    /// Resume/inspect a persisted run after interruption.
    RunResume { run_id: String },
    /// Ingest arXiv PDFs.
    IngestArxiv {
        #[arg(long)]
        query: String,
        #[arg(long, default_value_t = 5)]
        max_results: u32,
    },
    /// Ingest a local PDF.
    IngestPdf {
        #[arg(long)]
        path: PathBuf,
    },
    /// Human review of extracted formulas in a chunks JSONL file.
    ReviewFormulas {
        #[arg(long)]
        chunks: PathBuf,
        #[arg(long)]
        decision: Option<String>,
        #[arg(long)]
        corrected_latex: Option<String>,
        #[arg(long, default_value = "human")]
        reviewer: String,
    },
    /// Human review of APA citation metadata in a chunks JSONL file.
    ReviewCitations {
        #[arg(long)]
        chunks: PathBuf,
        #[arg(long)]
        decision: String,
        #[arg(long)]
        corrected_citation: Option<String>,
        #[arg(long, default_value = "human")]
        reviewer: String,
    },
    /// Validate formula extraction/review readiness for a chunks JSONL file.
    ValidateFormulas {
        #[arg(long)]
        chunks: PathBuf,
    },
    /// Record one human checkpoint decision for citation/formula/representation/plan/code/validation review.
    ReviewCheckpoint {
        #[arg(long)]
        phase: String,
        #[arg(long)]
        decision: String,
        #[arg(long, default_value = "require_high_risk_only")]
        policy: String,
        #[arg(long)]
        artifact_json: Option<String>,
        #[arg(long, default_value = "human")]
        reviewer: String,
        #[arg(long)]
        notes: Option<String>,
        #[arg(long)]
        run_id: Option<String>,
    },
    /// Run a full non-interactive human checkpoint workflow for source/mocked or CI review.
    ReviewWorkflow {
        #[arg(long, default_value = "require_all")]
        policy: String,
        #[arg(long, default_value = "approve")]
        decision: String,
        #[arg(long, default_value = "human")]
        reviewer: String,
        #[arg(long)]
        run_id: Option<String>,
        #[arg(long)]
        workspace: Option<String>,
    },
    /// Upload the Veritas OWL ontology into Fuseki/Jena.
    UploadOntology {
        #[arg(long)]
        path: Option<PathBuf>,
    },
    /// Generate a validated package by running the autonomous planner/code/test loop.
    GenerateCode {
        #[arg(long)]
        prompt: String,
        #[arg(long, default_value = "rust")]
        language: String,
        #[arg(long)]
        max_retries: Option<usize>,
    },
    /// Run the full autonomous reasoning, coding, and validation loop.
    Run {
        goal: String,
        #[arg(long, default_value = "rust")]
        language: String,
        #[arg(long)]
        max_retries: Option<usize>,
    },
    /// Search OpenSearch FAISS/HNSW and lexical fields.
    Search {
        query: String,
        #[arg(long, default_value_t = 10)]
        size: u32,
        #[arg(long, default_value = "hybrid")]
        mode: String,
    },
    /// Run a SPARQL query.
    Sparql {
        query: String,
    },
    /// Ask Veritas for an evidence-backed plan.
    Ask {
        prompt: String,
    },
    /// Ask Veritas for an evidence-backed plan.
    Plan {
        goal: String,
    },
    /// Directly call the configured vLLM role.
    Chat {
        #[arg(long, default_value = "planner")]
        role: String,
        prompt: String,
    },
}

#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();
    let http = Client::new();
    match cli.command.unwrap_or(Commands::Welcome) {
        Commands::Welcome => print_startup_screen(&http, &cli.api_url).await,
        Commands::Init | Commands::Configure => configure_interactive(),
        Commands::SetupValidate => validate_setup(),
        Commands::Deploy { models } => {
            print_logo();
            ensure_runtime_env()?;
            validate_setup()?;
            if models { gpu_validate()?; }
            let mut args = vec!["compose", "--env-file", ".veritas/runtime.env"];
            if models { args.extend(["--profile", "models", "--profile", "code-model", "--profile", "math-model"]); }
            args.extend(["up", "-d", "--build"]);
            run("docker", &args)
        },
        Commands::E2eFake { keep_running } => {
            if keep_running {
                run("bash", &["-lc", "VERITAS_E2E_KEEP_RUNNING=1 scripts/e2e/full-fake-vllm-e2e.sh"])
            } else {
                run("bash", &["scripts/e2e/full-fake-vllm-e2e.sh"])
            }
        },
        Commands::ValidateHost => run("bash", &["scripts/validate-host.sh"]),
        Commands::ProductionAccept { live_vllm } => {
            if live_vllm {
                run("bash", &["-lc", "VERITAS_REQUIRE_LIVE_VLLM_VALIDATION=true scripts/production-acceptance.sh"])
            } else {
                run("bash", &["scripts/production-acceptance.sh"])
            }
        },
        Commands::Prompt => prompt_shell(&http, &cli.api_url).await,
        Commands::Journey { command } => match command {
            JourneyCommands::Run { source, mode, goal, language, policy, max_retries } => {
                let mut body = json!({"mode": mode, "language": language, "policy": policy});
                if let Some(source_path) = source {
                    body["source"] = json!(source_path.to_string_lossy().to_string());
                }
                if let Some(goal_value) = goal { body["goal"] = json!(goal_value); }
                if let Some(retries) = max_retries { body["max_retries"] = json!(retries); }
                print_response(
                    http.post(format!("{}/journey/run", cli.api_url)).json(&body).send().await,
                    "api.journey.run",
                ).await
            }
            JourneyCommands::Status { run_id } => print_response(
                http.get(format!("{}/journey/{}/status", cli.api_url, run_id)).send().await,
                "api.journey.status",
            ).await,
            JourneyCommands::Review { run_id, phase, decision, notes, reviewer } => {
                let mut body = json!({"phase": phase, "decision": decision, "reviewer": reviewer});
                if let Some(value) = notes { body["notes"] = json!(value); }
                print_response(
                    http.post(format!("{}/journey/{}/review", cli.api_url, run_id)).json(&body).send().await,
                    "api.journey.review",
                ).await
            }
            JourneyCommands::Resume { run_id } => print_response(
                http.post(format!("{}/journey/{}/resume", cli.api_url, run_id)).send().await,
                "api.journey.resume",
            ).await,
            JourneyCommands::Report { run_id } => print_response(
                http.get(format!("{}/journey/{}/report", cli.api_url, run_id)).send().await,
                "api.journey.report",
            ).await,
        },
        Commands::Start {
            models,
            code_model,
            math_model,
        } => {
            print_logo();
            ensure_runtime_env()?;
            validate_setup()?;
            if models || code_model || math_model { gpu_validate()?; }
            let mut args = vec!["compose", "--env-file", ".veritas/runtime.env"];
            if models {
                args.extend(["--profile", "models"]);
            }
            if code_model {
                args.extend(["--profile", "code-model"]);
            }
            if math_model {
                args.extend(["--profile", "math-model"]);
            }
            args.extend(["up", "-d", "--build"]);
            run("docker", &args)?;
            print_start_success(&cli.api_url, models, code_model, math_model);
            Ok(())
        },
        Commands::Up => { ensure_runtime_env()?; run("docker", &["compose", "--env-file", ".veritas/runtime.env", "up", "-d", "--build"]) },
        Commands::Down => run("docker", &["compose", "--env-file", ".veritas/runtime.env", "down"]),
        Commands::Health => print_response(
            http.get(format!("{}/health", cli.api_url)).send().await,
            "api.health",
        )
        .await,
        Commands::Ready => print_response(
            http.get(format!("{}/ready", cli.api_url)).send().await,
            "api.ready",
        )
        .await,
        Commands::Models => print_response(
            http.get(format!("{}/models", cli.api_url)).send().await,
            "api.models",
        )
        .await,
        Commands::GpuInspect => gpu_inspect(),
        Commands::GpuValidate => gpu_validate(),
        Commands::OpenSearchMapping => print_response(
            http.get(format!("{}/opensearch/mapping", cli.api_url)).send().await,
            "api.opensearch.mapping",
        ).await,
        Commands::OpenSearchMigrate { dry_run } => print_response(
            http.post(format!("{}/opensearch/migrate", cli.api_url)).json(&json!({"dry_run": dry_run})).send().await,
            "api.opensearch.migrate",
        ).await,
        Commands::OpenSearchStatus => print_response(
            http.get(format!("{}/opensearch/status", cli.api_url)).send().await,
            "api.opensearch.status",
        ).await,
        Commands::GraphList => print_response(
            http.get(format!("{}/graphs", cli.api_url)).send().await,
            "api.graphs",
        ).await,
        Commands::GraphFacts => print_response(
            http.get(format!("{}/graph/facts", cli.api_url)).send().await,
            "api.graph.facts",
        ).await,
        Commands::GraphDescribe { graph_uri } => print_response(
            http.post(format!("{}/graph/describe", cli.api_url)).json(&json!({"graph_uri": graph_uri})).send().await,
            "api.graph.describe",
        ).await,
        Commands::GraphUpload { path, graph_uri, replace } => {
            let turtle = fs::read_to_string(&path).map_err(|error| anyhow!("failed to read Turtle file {:?}: {}", path, error))?;
            print_response(
                http.post(format!("{}/graph/upload", cli.api_url)).json(&json!({"graph_uri": graph_uri, "turtle": turtle, "replace": replace, "content_type": "text/turtle"})).send().await,
                "api.graph.upload",
            ).await
        },
        Commands::Search { query, size, mode } => {
            print_response(
                http.post(format!("{}/search", cli.api_url))
                    .json(&json!({"query": query, "size": size, "mode": mode}))
                    .send()
                    .await,
                "api.search",
            )
            .await
        },
        Commands::Sparql { query } => {
            print_response(
                http.post(format!("{}/sparql", cli.api_url))
                    .json(&json!({"query": query}))
                    .send()
                    .await,
                "api.sparql",
            )
            .await
        },
        Commands::Plan { goal } | Commands::Ask { prompt: goal } => {
            print_response(
                http.post(format!("{}/plan", cli.api_url))
                    .json(&json!({"goal": goal}))
                    .send()
                    .await,
                "api.plan",
            )
            .await
        },
        Commands::Chat { role, prompt } => {
            print_response(
                http.post(format!("{}/llm/chat", cli.api_url))
                    .json(&json!({"role": role, "prompt": prompt}))
                    .send()
                    .await,
                "api.llm.chat",
            )
            .await
        },
        Commands::EvidenceRegistryStatus { path } => print_response(
            http.post(format!("{}/evidence-registry/status", cli.api_url))
                .json(&json!({"path": path.to_string_lossy().to_string()}))
                .send()
                .await,
            "api.evidence_registry.status",
        ).await,
        Commands::MathToCode { formula_id, formula_record_id, citation_record_id, evidence_manifest_path, formula_latex, prompt, language, max_retries, allow_exploratory_unverified } => {
            let mut body = json!({"formula_id": formula_id, "formula_record_id": formula_record_id, "citation_record_id": citation_record_id, "evidence_manifest_path": evidence_manifest_path.as_ref().map(|path| path.to_string_lossy().to_string()), "formula_latex": formula_latex, "prompt": prompt, "language": language, "allow_exploratory_unverified": allow_exploratory_unverified});
            if let Some(retries) = max_retries { body["max_retries"] = json!(retries); }
            let first = http.post(format!("{}/math-to-code", cli.api_url)).json(&body).send().await;
            match first {
                Ok(resp) => {
                    let status = resp.status();
                    let value: Value = resp.json().await.unwrap_or_else(|_| json!({"ok": false, "error": "invalid json response"}));
                    if status.as_u16() == 202 && value.get("status").and_then(Value::as_str) == Some("awaiting_human_checkpoint") {
                        println!("\nVeritas requires human review before code generation.\n");
                        println!("{}", serde_json::to_string_pretty(&value["checkpoint"]).unwrap_or_else(|_| value["checkpoint"].to_string()));
                        let decision = prompt_default("Approve this representation-first math analysis? (approve/reject)", "approve")?;
                        if decision.trim().eq_ignore_ascii_case("approve") {
                            body["human_decision"] = json!({"decision": "approve", "reviewer": "cli-human"});
                            print_response(http.post(format!("{}/math-to-code", cli.api_url)).json(&body).send().await, "api.math_to_code.approved").await
                        } else {
                            println!("Human rejected the math-to-code checkpoint. No code was generated.");
                            Ok(())
                        }
                    } else {
                        println!("{}", serde_json::to_string_pretty(&value).unwrap_or_else(|_| value.to_string()));
                        Ok(())
                    }
                }
                Err(error) => Err(anyhow!("api.math_to_code request failed: {}", error)),
            }
        },
        Commands::RunStatus { run_id } => print_response(
            http.get(format!("{}/status/{}", cli.api_url, run_id)).send().await,
            "api.run.status",
        ).await,
        Commands::RunCancel { run_id } => print_response(
            http.post(format!("{}/run/{}/cancel", cli.api_url, run_id)).send().await,
            "api.run.cancel",
        ).await,
        Commands::RunResume { run_id } => print_response(
            http.post(format!("{}/run/{}/resume", cli.api_url, run_id)).send().await,
            "api.run.resume",
        ).await,
        Commands::ReviewFormulas { chunks, decision, corrected_latex, reviewer } => {
            let mut args = vec!["compose", "--env-file", ".veritas/runtime.env", "run", "--rm", "ingestion", "python", "-m", "veritas_ingest.cli", "review-formulas", "--chunks"];
            let chunks_str = chunks.to_string_lossy().to_string();
            args.push(&chunks_str);
            let decision_str;
            if let Some(value) = decision {
                args.push("--decision");
                decision_str = value;
                args.push(&decision_str);
            }
            let corrected_latex_str;
            if let Some(value) = corrected_latex {
                args.push("--corrected-latex");
                corrected_latex_str = value;
                args.push(&corrected_latex_str);
            }
            args.push("--reviewer");
            args.push(&reviewer);
            run("docker", &args)
        },
        Commands::ReviewCitations { chunks, decision, corrected_citation, reviewer } => {
            let mut args = vec!["compose", "--env-file", ".veritas/runtime.env", "run", "--rm", "ingestion", "python", "-m", "veritas_ingest.cli", "review-citations", "--chunks"];
            let chunks_str = chunks.to_string_lossy().to_string();
            args.push(&chunks_str);
            args.push("--decision");
            args.push(&decision);
            let corrected_citation_str;
            if let Some(value) = corrected_citation {
                args.push("--corrected-citation");
                corrected_citation_str = value;
                args.push(&corrected_citation_str);
            }
            args.push("--reviewer");
            args.push(&reviewer);
            run("docker", &args)
        },
        Commands::ValidateFormulas { chunks } => {
            let chunks_str = chunks.to_string_lossy().to_string();
            run("docker", &["compose", "--env-file", ".veritas/runtime.env", "run", "--rm", "ingestion", "python", "-m", "veritas_ingest.cli", "validate-formulas", "--chunks", &chunks_str])
        },
        Commands::ReviewCheckpoint { phase, decision, policy, artifact_json, reviewer, notes, run_id } => {
            let mut args = vec!["compose", "--env-file", ".veritas/runtime.env", "run", "--rm", "ingestion", "python", "-m", "veritas_ingest.cli", "review-checkpoint", "--phase"];
            args.push(&phase);
            args.push("--decision");
            args.push(&decision);
            args.push("--policy");
            args.push(&policy);
            let artifact_json_str;
            if let Some(value) = artifact_json { args.push("--artifact-json"); artifact_json_str = value; args.push(&artifact_json_str); }
            args.push("--reviewer");
            args.push(&reviewer);
            let notes_str;
            if let Some(value) = notes { args.push("--notes"); notes_str = value; args.push(&notes_str); }
            let run_id_str;
            if let Some(value) = run_id { args.push("--run-id"); run_id_str = value; args.push(&run_id_str); }
            run("docker", &args)
        },
        Commands::ReviewWorkflow { policy, decision, reviewer, run_id, workspace } => {
            let mut args = vec!["compose", "--env-file", ".veritas/runtime.env", "run", "--rm", "ingestion", "python", "-m", "veritas_ingest.cli", "review-workflow", "--policy"];
            args.push(&policy);
            args.push("--decision");
            args.push(&decision);
            args.push("--reviewer");
            args.push(&reviewer);
            let run_id_str;
            if let Some(value) = run_id { args.push("--run-id"); run_id_str = value; args.push(&run_id_str); }
            let workspace_str;
            if let Some(value) = workspace { args.push("--workspace"); workspace_str = value; args.push(&workspace_str); }
            run("docker", &args)
        },
        Commands::IngestArxiv { query, max_results } => run(
            "docker",
            &[
                "compose",
                "--env-file",
                ".veritas/runtime.env",
                "run",
                "--rm",
                "ingestion",
                "python",
                "-m",
                "veritas_ingest.cli",
                "ingest-arxiv",
                "--query",
                &query,
                "--max-results",
                &max_results.to_string(),
            ],
        ),
        Commands::IngestPdf { path } => {
            let container_path = stage_pdf_for_container(&path)?;
            run(
                "docker",
                &[
                    "compose",
                    "--env-file",
                    ".veritas/runtime.env",
                    "run",
                    "--rm",
                    "ingestion",
                    "python",
                    "-m",
                    "veritas_ingest.cli",
                    "ingest-pdf",
                    "--path",
                    &container_path,
                ],
            )
        },
        Commands::UploadOntology { path } => {
            let mut args = vec![
                "compose",
                "--env-file",
                ".veritas/runtime.env",
                "run",
                "--rm",
                "ingestion",
                "python",
                "-m",
                "veritas_ingest.cli",
                "upload-ontology",
            ];
            let staged_path;
            if let Some(path) = path {
                staged_path = stage_ontology_for_container(&path)?;
                args.push("--path");
                args.push(&staged_path);
            }
            run("docker", &args)
        },
        Commands::GenerateCode { prompt, language, max_retries } => {
            let mut body = json!({"goal": prompt, "language": language});
            if let Some(retries) = max_retries { body["max_retries"] = json!(retries); }
            print_response(
                http.post(format!("{}/run", cli.api_url))
                    .json(&body)
                    .send()
                    .await,
                "api.run",
            )
            .await
        },
        Commands::Run { goal, language, max_retries } => {
            let mut body = json!({"goal": goal, "language": language});
            if let Some(retries) = max_retries { body["max_retries"] = json!(retries); }
            print_response(
                http.post(format!("{}/run", cli.api_url))
                    .json(&body)
                    .send()
                    .await,
                "api.run",
            )
            .await
        },
    }
}

fn stage_pdf_for_container(path: &Path) -> Result<String> {
    if !path.exists() {
        return Err(anyhow!(
            "PDF path does not exist: {:?}. Provide a local PDF path or use ingest-arxiv.",
            path
        ));
    }
    if path.extension().and_then(|value| value.to_str()).unwrap_or_default().to_lowercase()
        != "pdf"
    {
        return Err(anyhow!(
            "input file is not a PDF: {:?}. Veritas ingestion currently accepts .pdf files.",
            path
        ));
    }
    let file_name = path
        .file_name()
        .and_then(|value| value.to_str())
        .ok_or_else(|| anyhow!("PDF file name is not valid UTF-8: {:?}", path))?;
    let upload_dir = Path::new("data/papers/uploads");
    fs::create_dir_all(upload_dir)?;
    let staged = upload_dir.join(file_name);
    fs::copy(path, &staged).map_err(|error| {
        anyhow!(
            "failed to stage PDF {:?} into {:?}: {}",
            path,
            staged,
            error
        )
    })?;
    println!("Staged PDF for container ingestion: {:?}", staged);
    Ok(format!("/workspace/data/papers/uploads/{}", file_name))
}

fn stage_ontology_for_container(path: &Path) -> Result<String> {
    if !path.exists() {
        return Err(anyhow!(
            "Ontology path does not exist: {:?}. Provide an OWL/RDF/Turtle file.",
            path
        ));
    }
    let file_name = path
        .file_name()
        .and_then(|value| value.to_str())
        .ok_or_else(|| anyhow!("Ontology file name is not valid UTF-8: {:?}", path))?;
    let ontology_dir = Path::new("packages/ontology/uploads");
    fs::create_dir_all(ontology_dir)?;
    let staged = ontology_dir.join(file_name);
    fs::copy(path, &staged).map_err(|error| {
        anyhow!(
            "failed to stage ontology {:?} into {:?}: {}",
            path,
            staged,
            error
        )
    })?;
    println!("Staged ontology for container upload: {:?}", staged);
    Ok(format!("/workspace/ontology/uploads/{}", file_name))
}

async fn print_startup_screen(http: &Client, api_url: &str) -> Result<()> {
    print_logo();
    print_system_status(http, api_url).await;
    print_knowledge_graph_status(http, api_url).await;
    print_model_status(http, api_url).await;
    print_menu();
    Ok(())
}

fn print_logo() {
    println!("═══════════════════════════════════════════════════════════════════");
    println!("{}", VERITAS_LOGO.trim_matches('\n'));
    println!("\n{:^67}\n", MOTTO);
    println!("      Math-heavy evidence-backed research and development");
    println!("                software engineering agent\n");
    println!("═══════════════════════════════════════════════════════════════════\n");
}

async fn print_system_status(http: &Client, api_url: &str) {
    println!("System Status");
    println!("─────────────");
    match http.get(format!("{}/ready", api_url.trim_end_matches('/'))).send().await {
        Ok(response) if response.status().is_success() || response.status().as_u16() == 503 => {
            match response.json::<Value>().await {
                Ok(value) => {
                    let checks = value.get("checks").unwrap_or(&Value::Null);
                    print_service_check(checks, "opensearch", "OpenSearch FAISS/HNSW");
                    print_service_check(checks, "fuseki", "Jena Fuseki Graph");
                    print_service_static("Openllet Reasoner", true, "offline reasoner container configured");
                    print_service_static("OWL-DL Ontology Loaded", true, "run Upload / Update Ontology to refresh");
                    print_service_check(checks, "embedding", "Embedding Service Ready");
                    print_service_static("Retrieval Pipeline Ready", true, "OpenSearch + embeddings + Fuseki configured");
                    print_service_check(checks, "vllm_planner", "vLLM Planner Model");
                    print_service_check(checks, "vllm_code", "vLLM Code Model");
                    print_service_check(checks, "vllm_math", "vLLM Math Model");
                }
                Err(error) => println!("! Could not decode readiness response: {error}"),
            }
        }
        Ok(response) => println!("! API returned HTTP {} for readiness", response.status()),
        Err(error) => {
            println!("! API unavailable at {api_url}: {error}");
            println!("  Start the stack with: veritas start --models");
        }
    }
    println!();
}

fn print_service_check(checks: &Value, key: &str, label: &str) {
    let item = checks.get(key).unwrap_or(&Value::Null);
    let ok = item.get("ok").and_then(Value::as_bool).unwrap_or(false);
    let marker = if ok { "✓" } else { "!" };
    println!("{marker} {label}");
    if !ok {
        let message = item.get("message").and_then(Value::as_str).unwrap_or("not reachable");
        println!("    {message}");
    }
}

fn print_service_static(label: &str, ok: bool, note: &str) {
    let marker = if ok { "✓" } else { "!" };
    println!("{marker} {label}");
    if !note.is_empty() && !ok {
        println!("    {note}");
    }
}

async fn print_knowledge_graph_status(http: &Client, api_url: &str) {
    println!("Knowledge Graph Status");
    println!("──────────────────────");
    match http
        .get(format!("{}/graph/status", api_url.trim_end_matches('/')))
        .send()
        .await
    {
        Ok(response) if response.status().is_success() => match response.json::<Value>().await {
            Ok(value) => {
                let counts = value.get("counts").unwrap_or(&Value::Null);
                print_count(counts, "objectives", "Objectives");
                print_count(counts, "plans", "Plans");
                print_count(counts, "tasks", "Tasks");
                print_count(counts, "risks", "Risks");
                print_count(counts, "invariants", "Invariants");
                print_count(counts, "evidence_items", "Evidence Items");
                print_count(counts, "validation_checks", "Validation Checks");
                println!("\nOntology:\n  {}", value.pointer("/ontology/name").and_then(Value::as_str).unwrap_or("Veritas OWL-DL"));
                println!("\nReasoner:\n  {}", value.pointer("/reasoner/name").and_then(Value::as_str).unwrap_or("Openllet"));
                println!("\nGraph:\n  Fuseki");
                println!("\nVector Memory:\n  OpenSearch FAISS/HNSW");
            }
            Err(error) => println!("! Could not decode graph status: {error}"),
        },
        _ => {
            println!("Objectives:                  unknown");
            println!("Plans:                       unknown");
            println!("Tasks:                       unknown");
            println!("Risks:                       unknown");
            println!("Invariants:                  unknown");
            println!("Evidence Items:              unknown");
            println!("Validation Checks:           unknown");
            println!("\nGraph status unavailable until API and Fuseki are running.");
        }
    }
    println!();
}

async fn print_model_status(http: &Client, api_url: &str) {
    println!("Model Routing");
    println!("─────────────");
    match http.get(format!("{}/models", api_url.trim_end_matches('/'))).send().await {
        Ok(response) if response.status().is_success() => match response.json::<Value>().await {
            Ok(value) => {
                println!("Serving:   vLLM OpenAI-compatible endpoints");
                println!("Planner:   {}", value.pointer("/planner/huggingface_model_id").and_then(Value::as_str).unwrap_or(DEFAULT_PLANNER_MODEL));
                println!("Code:      {}", value.pointer("/code_generation/primary/huggingface_model_id").and_then(Value::as_str).unwrap_or(DEFAULT_CODE_MODEL));
                println!("Math:      {}", value.pointer("/math_reasoning/primary/huggingface_model_id").and_then(Value::as_str).unwrap_or(DEFAULT_MATH_MODEL));
                println!("Embedding: {}", value.pointer("/embeddings/model").and_then(Value::as_str).unwrap_or(DEFAULT_EMBEDDING_MODEL));
            }
            Err(error) => println!("! Could not decode model routing: {error}"),
        },
        _ => println!("Model routing unavailable until API is running. Configure with `veritas init`."),
    }
    println!();
}

fn print_count(counts: &Value, key: &str, label: &str) {
    let value = counts.get(key).and_then(Value::as_u64).unwrap_or(0);
    println!("{label:<24}{value:>8}");
}

fn print_menu() {
    println!("What would you like to do?\n");
    println!("[1] Ingest arXiv Research");
    println!("[2] Upload Local PDFs");
    println!("[3] Upload / Update Ontology");
    println!("[4] Search Research Corpus");
    println!("[5] Generate Code from Research");
    println!("[6] Run Mathematical Discovery Workflow");
    println!("[7] View Evidence Graph");
    println!("[8] Validate Generated Artifacts");
    println!("[9] Configuration\n");
    println!("Modes");
    println!("─────");
    println!("Research Mode:     ingest papers, discover invariants, representation search");
    println!("Engineering Mode:  generate code, tests, packages, validation reports");
    println!("Operations Mode:   deployment, runtime, observability, runbooks");
    println!("Autonomous Mode:   evidence → ontology → plan → code → validation\n");
    println!("Examples");
    println!("────────");
    println!("veritas init");
    println!("veritas start --models");
    println!("veritas ingest-arxiv --query \"cat:cs.AI OR cat:math.OC\" --max-results 3");
    println!("veritas ingest-pdf --path ./paper.pdf");
    println!("veritas ask \"Build a distributed GPU implementation of paper X\"\n");
    print!("veritas > ");
    let _ = io::stdout().flush();
}

fn print_start_success(api_url: &str, models: bool, code_model: bool, math_model: bool) {
    println!("\nVeritas stack start requested.");
    println!("API: {api_url}");
    if models || code_model || math_model {
        println!("Model profiles enabled:");
        if models { println!("  - planner vLLM"); }
        if code_model { println!("  - code vLLM"); }
        if math_model { println!("  - math vLLM"); }
    } else {
        println!("Model profiles were not started. Use `veritas start --models` for planner vLLM.");
    }
    println!("\nNext:");
    println!("  veritas ready");
    println!("  veritas models");
    println!("  veritas upload-ontology");
    println!("  veritas ingest-arxiv --query \"cat:cs.AI OR cat:math.OC\" --max-results 3");
}

fn configure_interactive() -> Result<()> {
    print_logo();
    println!("Veritas setup + deployment wizard");
    println!("────────────────────────────────");
    println!("This wizard configures models, GPUs, services, ingestion, ontology upload, and generated-code paths.");
    println!("vLLM is the local model serving solution. Paste any Hugging Face model ID to override defaults.\n");

    println!("1/8 — Model roles");
    let hf_token = prompt_default("Hugging Face token (optional; can also use HF_TOKEN)", "")?;
    let planner = prompt_default("Planner model", DEFAULT_PLANNER_MODEL)?;
    let code = prompt_default("Code generation model", DEFAULT_CODE_MODEL)?;
    let code_fallback = prompt_default("Code fallback model", DEFAULT_CODE_FALLBACK_MODEL)?;
    println!("\nMath reasoning choices:");
    println!("  1. {}", DEFAULT_MATH_MODEL);
    println!("  2. {}", DEFAULT_MATH_LARGE_MODEL);
    println!("  3. Custom Hugging Face model ID");
    let math_choice = prompt_default("Math model choice", "1")?;
    let math = match math_choice.trim() {
        "2" => DEFAULT_MATH_LARGE_MODEL.to_string(),
        "3" => prompt_default("Custom math model", DEFAULT_MATH_MODEL)?,
        other if other.contains('/') => other.to_string(),
        _ => DEFAULT_MATH_MODEL.to_string(),
    };
    let embedding = prompt_default("Embedding model", DEFAULT_EMBEDDING_MODEL)?;

    println!("\n2/8 — Hardware and vLLM GPU layout");
    let gpu_count = prompt_default("Number of NVIDIA GPUs available (0 allowed)", "1")?;
    let gpu_id = prompt_default("Default GPU device id", "0")?;
    let planner_gpu_ids = prompt_default("Planner GPU device IDs", &gpu_id)?;
    let code_gpu_ids = prompt_default("Code model GPU device IDs", &gpu_id)?;
    let math_gpu_ids = prompt_default("Math model GPU device IDs", &gpu_id)?;
    let planner_tp = prompt_default("Planner tensor_parallel_size", "1")?;
    let code_tp = prompt_default("Code tensor_parallel_size", "1")?;
    let math_tp = prompt_default("Math tensor_parallel_size", "1")?;
    let planner_pp = prompt_default("Planner pipeline_parallel_size", "1")?;
    let code_pp = prompt_default("Code pipeline_parallel_size", "1")?;
    let math_pp = prompt_default("Math pipeline_parallel_size", "1")?;
    let planner_mem = prompt_default("Planner GPU memory utilization", "0.30")?;
    let code_mem = prompt_default("Code GPU memory utilization", "0.60")?;
    let math_mem = prompt_default("Math GPU memory utilization", "0.30")?;
    let require_models = prompt_default("Require vLLM models for readiness? true/false", "true")?;

    println!("\n3/8 — Services");
    let opensearch_port = prompt_default("OpenSearch host port", "9200")?;
    let opensearch_index = prompt_default("OpenSearch index", "veritas-papers")?;
    let fuseki_port = prompt_default("Jena Fuseki host port", "3030")?;
    let fuseki_dataset = prompt_default("Jena Fuseki dataset", "veritas")?;
    let shacl_port = prompt_default("SHACL service host port", "8088")?;

    println!("\n4/8 — Ingestion and ontology upload");
    let upload_docs = prompt_default("Upload documents during setup? true/false", "false")?;
    let docs_path = if truthy(&upload_docs) { prompt_default("Document file/directory/arXiv query", "data/papers/uploads")? } else { String::new() };
    let upload_ontology = prompt_default("Upload ontology/RDF/OWL/TTL during setup? true/false", "true")?;
    let ontology_path = if truthy(&upload_ontology) { prompt_default("Ontology file or directory", "packages/ontology/veritas.owl")? } else { String::new() };
    let chunk_words = prompt_default("Prose chunk target words", "25")?;
    let formula_extraction = prompt_default("Extract formulas and preserve formula chunks? true/false", "true")?;
    let human_loop = prompt_default("Human-in-the-loop checkpoint policy (require_all/require_high_risk_only/auto_approve)", "require_high_risk_only")?;

    println!("\n5/8 — Project and code-design setup");
    println!("Veritas will enforce a Haskell-inspired FP style by default: pure domain core, referential transparency, composable functions, higher-order functions, dispatch tables, and isolated side effects.");
    let project_dir = prompt_default("Project directory for generated runs", "data/runs")?;
    let architecture_style = prompt_default("Architecture style", "functional-core-imperative-shell")?;
    let pure_domain_core = prompt_default("Require pure domain core? true/false", "true")?;
    let referential_transparency = prompt_default("Require referential transparency where practical? true/false", "true")?;
    let dispatch_tables = prompt_default("Prefer dispatch tables over long conditionals? true/false", "true")?;
    let higher_order = prompt_default("Prefer higher-order functions/composition? true/false", "true")?;
    let side_effect_boundaries = prompt_default("Isolate I/O and mutation behind boundary functions? true/false", "true")?;

    let contents = format!(
        r#"# Generated by `veritas init`. Do not commit this file.
COMPOSE_PROJECT_NAME=veritas
VERITAS_API_PORT=8080
VERITAS_OPENSEARCH_PORT={opensearch_port}
VERITAS_OPENSEARCH_DASHBOARDS_PORT=5601
VERITAS_FUSEKI_PORT={fuseki_port}
VERITAS_FUSEKI_DATASET={fuseki_dataset}
VERITAS_SHACL_PORT={shacl_port}
VERITAS_EMBEDDING_PORT=8090
VERITAS_OPENSEARCH_VERSION=2.19.5
VERITAS_FUSEKI_IMAGE=stain/jena-fuseki:5.5.0
VERITAS_VLLM_IMAGE={vllm_image}
HF_TOKEN={hf_token}
VERITAS_MODEL_PROVIDER=vllm
VERITAS_MODEL_SERVING_PROVIDER=vllm
VERITAS_REQUIRE_MODELS={require_models}
VERITAS_VLLM_DTYPE=auto
VERITAS_VLLM_ENABLE_CUDA_COMPATIBILITY=1
VERITAS_GPU_COUNT={gpu_count}
VERITAS_GPU_DEVICE_ID={gpu_id}
VERITAS_PLANNER_GPU_DEVICE_IDS={planner_gpu_ids}
VERITAS_CODE_GPU_DEVICE_IDS={code_gpu_ids}
VERITAS_MATH_GPU_DEVICE_IDS={math_gpu_ids}
VERITAS_PLANNER_TENSOR_PARALLEL_SIZE={planner_tp}
VERITAS_CODE_TENSOR_PARALLEL_SIZE={code_tp}
VERITAS_MATH_TENSOR_PARALLEL_SIZE={math_tp}
VERITAS_PLANNER_PIPELINE_PARALLEL_SIZE={planner_pp}
VERITAS_CODE_PIPELINE_PARALLEL_SIZE={code_pp}
VERITAS_MATH_PIPELINE_PARALLEL_SIZE={math_pp}
VERITAS_PLANNER_MODEL={planner}
VERITAS_PLANNER_SERVED_MODEL_NAME=veritas-planner
VERITAS_PLANNER_VLLM_URL=http://vllm-planner:8000
VERITAS_PLANNER_VLLM_PORT=8001
VERITAS_PLANNER_MAX_MODEL_LEN=32768
VERITAS_PLANNER_GPU_MEMORY_UTILIZATION={planner_mem}
VERITAS_CODE_MODEL={code}
VERITAS_CODE_FALLBACK_MODEL={code_fallback}
VERITAS_CODE_SERVED_MODEL_NAME=veritas-code
VERITAS_CODE_VLLM_URL=http://vllm-code:8000
VERITAS_CODE_VLLM_PORT=8002
VERITAS_CODE_MAX_MODEL_LEN=32768
VERITAS_CODE_GPU_MEMORY_UTILIZATION={code_mem}
VERITAS_MATH_MODEL={math}
VERITAS_MATH_LARGE_MODEL={math_large}
VERITAS_MATH_SERVED_MODEL_NAME=veritas-math
VERITAS_MATH_VLLM_URL=http://vllm-math:8000
VERITAS_MATH_VLLM_PORT=8003
VERITAS_MATH_MAX_MODEL_LEN=32768
VERITAS_MATH_GPU_MEMORY_UTILIZATION={math_mem}
VERITAS_REMOTE_MODEL_ENABLED=false
VERITAS_REMOTE_MODEL_BASE_URL=
VERITAS_REMOTE_MODEL_API_KEY=
VERITAS_REMOTE_MODEL_NAME=
VERITAS_EMBEDDING_MODEL={embedding}
VERITAS_EMBEDDING_NORMALIZE=true
VERITAS_EMBEDDING_DEVICE=auto
VERITAS_EMBEDDING_BATCH_SIZE=16
VERITAS_OPENSEARCH_INDEX={opensearch_index}-read
VERITAS_OPENSEARCH_INDEX_BASE={opensearch_index}
VERITAS_OPENSEARCH_READ_ALIAS={opensearch_index}-read
VERITAS_OPENSEARCH_WRITE_ALIAS={opensearch_index}-write
VERITAS_OPENSEARCH_VERSIONED_INDEX={opensearch_index}-v1
VERITAS_OPENSEARCH_MAPPING_VERSION=v1
VERITAS_OPENSEARCH_VECTOR_FIELD=embedding
VERITAS_OPENSEARCH_VECTOR_DIMENSION=768
VERITAS_GRAPH_ONTOLOGY_URI=urn:veritas:graph:ontology
VERITAS_GRAPH_DOCUMENT_BASE_URI=urn:veritas:graph:document
VERITAS_GRAPH_RUN_BASE_URI=urn:veritas:graph:run
VERITAS_GRAPH_VALIDATION_BASE_URI=urn:veritas:graph:validation
VERITAS_RUNS_DIR=/workspace/{project_dir}
VERITAS_PROJECT_DIR={project_dir}
VERITAS_ARCHITECTURE_STYLE={architecture_style}
VERITAS_CODE_STYLE=functional-composition
VERITAS_REQUIRE_PURE_DOMAIN_CORE={pure_domain_core}
VERITAS_REQUIRE_REFERENTIAL_TRANSPARENCY={referential_transparency}
VERITAS_USE_DISPATCH_TABLES={dispatch_tables}
VERITAS_USE_HIGHER_ORDER_FUNCTIONS={higher_order}
VERITAS_ISOLATE_SIDE_EFFECT_BOUNDARIES={side_effect_boundaries}
VERITAS_AGENT_MAX_RETRIES=2
VERITAS_COMMAND_TIMEOUT_SECS=180
VERITAS_COMMAND_RUNNER=local
VERITAS_SANDBOX_IMAGE=veritas-sandbox-rust:latest
VERITAS_GOVERNANCE_MODE=enforce
VERITAS_REMOTE_MODEL_API_KEY_ENV=VERITAS_REMOTE_MODEL_API_KEY
VERITAS_SETUP_UPLOAD_DOCS={upload_docs}
VERITAS_SETUP_DOCS_PATH={docs_path}
VERITAS_SETUP_UPLOAD_ONTOLOGY={upload_ontology}
VERITAS_SETUP_ONTOLOGY_PATH={ontology_path}
VERITAS_CHUNK_TARGET_WORDS={chunk_words}
VERITAS_EXTRACT_FORMULAS={formula_extraction}
VERITAS_HUMAN_LOOP_POLICY={human_loop}
VERITAS_FUSEKI_ADMIN_PASSWORD=admin
OPENSEARCH_INITIAL_ADMIN_PASSWORD=VeritasAdmin123!
"#,
        vllm_image = DEFAULT_VLLM_IMAGE,
        hf_token = hf_token,
        require_models = require_models,
        gpu_count = gpu_count,
        gpu_id = gpu_id,
        planner_gpu_ids = planner_gpu_ids,
        code_gpu_ids = code_gpu_ids,
        math_gpu_ids = math_gpu_ids,
        planner_tp = planner_tp,
        code_tp = code_tp,
        math_tp = math_tp,
        planner_pp = planner_pp,
        code_pp = code_pp,
        math_pp = math_pp,
        planner_mem = planner_mem,
        code_mem = code_mem,
        math_mem = math_mem,
        planner = planner,
        code = code,
        code_fallback = code_fallback,
        math = math,
        math_large = DEFAULT_MATH_LARGE_MODEL,
        embedding = embedding,
        opensearch_port = opensearch_port,
        opensearch_index = opensearch_index,
        fuseki_port = fuseki_port,
        fuseki_dataset = fuseki_dataset,
        shacl_port = shacl_port,
        project_dir = project_dir,
        architecture_style = architecture_style,
        pure_domain_core = pure_domain_core,
        referential_transparency = referential_transparency,
        dispatch_tables = dispatch_tables,
        higher_order = higher_order,
        side_effect_boundaries = side_effect_boundaries,
        upload_docs = upload_docs,
        docs_path = docs_path,
        upload_ontology = upload_ontology,
        ontology_path = ontology_path,
        chunk_words = chunk_words,
        formula_extraction = formula_extraction,
        human_loop = human_loop
    );
    fs::create_dir_all(".veritas")?;
    fs::write(".veritas/runtime.env", &contents)?;
    let config_yaml = format!("project:\n  generated_by: veritas init\n  project_dir: {project_dir}\n  architecture_style: {architecture_style}\nmodels:\n  planner: {planner}\n  code: {code}\n  code_fallback: {code_fallback}\n  math: {math}\n  embeddings: {embedding}\nhardware:\n  gpu_count: {gpu_count}\n  planner_gpu_ids: {planner_gpu_ids}\n  code_gpu_ids: {code_gpu_ids}\n  math_gpu_ids: {math_gpu_ids}\n  planner_tensor_parallel_size: {planner_tp}\n  code_tensor_parallel_size: {code_tp}\n  math_tensor_parallel_size: {math_tp}\nservices:\n  opensearch_index: {opensearch_index}\n  fuseki_dataset: {fuseki_dataset}\n  shacl_port: {shacl_port}\ningestion:\n  upload_docs: {upload_docs}\n  docs_path: {docs_path}\n  upload_ontology: {upload_ontology}\n  ontology_path: {ontology_path}\n  chunk_target_words: {chunk_words}\n  extract_formulas: {formula_extraction}\nhuman_loop:\n  policy: {human_loop}\n");
    fs::write(".veritas/config.yaml", config_yaml)?;
    fs::write(".veritas/docker-compose.override.yaml", "# Generated by veritas init. Runtime values are in .veritas/runtime.env\n")?;
    println!("\n✓ Wrote .veritas/runtime.env and .veritas/config.yaml.");
    println!("✓ No .env.example is required; all deployment values were captured by the CLI.");
    println!("Next: veritas deploy --models && veritas ready");
    Ok(())
}

fn truthy(value: &str) -> bool {
    matches!(value.trim().to_ascii_lowercase().as_str(), "1" | "true" | "yes" | "y" | "on")
}

fn prompt_default(label: &str, default: &str) -> Result<String> {
    if default.is_empty() {
        print!("{label}: ");
    } else {
        print!("{label} [{default}]: ");
    }
    io::stdout().flush()?;
    let mut input = String::new();
    io::stdin().read_line(&mut input)?;
    let value = input.trim();
    if value.is_empty() {
        Ok(default.to_string())
    } else {
        Ok(value.to_string())
    }
}

fn ensure_runtime_env() -> Result<()> {
    if !Path::new(".veritas/runtime.env").exists() {
        println!("No .veritas/runtime.env found. Starting Veritas setup wizard.");
        configure_interactive()?;
    }
    Ok(())
}

fn validate_setup() -> Result<()> {
    if !Path::new(".veritas/config.yaml").exists() || !Path::new(".veritas/runtime.env").exists() {
        return Err(anyhow!("Veritas setup is incomplete. Run `veritas init` first."));
    }
    let cfg = fs::read_to_string(".veritas/config.yaml")?;
    if !cfg.contains("models:") || !cfg.contains("services:") || !cfg.contains("hardware:") {
        return Err(anyhow!(".veritas/config.yaml is missing required models/services/hardware sections."));
    }
    let env_text = fs::read_to_string(".veritas/runtime.env")?;
    let required = [
        "VERITAS_PLANNER_MODEL",
        "VERITAS_CODE_MODEL",
        "VERITAS_MATH_MODEL",
        "VERITAS_OPENSEARCH_INDEX",
        "VERITAS_FUSEKI_DATASET",
        "VERITAS_GRAPH_ONTOLOGY_URI",
        "VERITAS_PROJECT_DIR",
    ];
    let missing: Vec<&str> = required.iter().copied().filter(|key| runtime_env_value(&env_text, key).is_none()).collect();
    if !missing.is_empty() {
        return Err(anyhow!(".veritas/runtime.env is missing required keys: {}", missing.join(", ")));
    }
    println!("✓ Veritas setup files are present and structurally valid.");
    Ok(())
}


fn gpu_inspect() -> Result<()> {
    println!("GPU Inventory");
    println!("─────────────");
    match Command::new("nvidia-smi").args(["--query-gpu=index,name,memory.total,memory.free,driver_version", "--format=csv,noheader,nounits"]).output() {
        Ok(output) if output.status.success() => {
            let text = String::from_utf8_lossy(&output.stdout);
            if text.trim().is_empty() { println!("No NVIDIA GPUs reported by nvidia-smi."); } else { println!("{text}"); }
            Ok(())
        }
        Ok(output) => {
            println!("nvidia-smi returned non-zero status. stderr:\n{}", String::from_utf8_lossy(&output.stderr));
            println!("Veritas can still run in thin-cpu or remote-model mode.");
            Ok(())
        }
        Err(error) => {
            println!("nvidia-smi is unavailable: {error}");
            println!("Veritas can still run in thin-cpu, ingestion-only, query-only, or remote-model mode.");
            Ok(())
        }
    }
}

fn gpu_validate() -> Result<()> {
    ensure_runtime_env()?;
    let env_text = fs::read_to_string(".veritas/runtime.env")?;
    let gpu_count = runtime_env_value(&env_text, "VERITAS_GPU_COUNT").unwrap_or_else(|| "0".to_string()).parse::<usize>().unwrap_or(0);
    let strict = runtime_env_value(&env_text, "VERITAS_STRICT_GPU_VALIDATE").map(|v| truthy(&v)).unwrap_or(false);
    let actual_inventory = detect_gpu_inventory();
    let actual_count = actual_inventory.as_ref().map(|v| v.len()).unwrap_or(0);
    let roles = [
        ("planner", "VERITAS_PLANNER_GPU_DEVICE_IDS", "VERITAS_PLANNER_TENSOR_PARALLEL_SIZE", "VERITAS_PLANNER_PIPELINE_PARALLEL_SIZE", "VERITAS_PLANNER_GPU_MEMORY_UTILIZATION", "VERITAS_PLANNER_MODEL"),
        ("code", "VERITAS_CODE_GPU_DEVICE_IDS", "VERITAS_CODE_TENSOR_PARALLEL_SIZE", "VERITAS_CODE_PIPELINE_PARALLEL_SIZE", "VERITAS_CODE_GPU_MEMORY_UTILIZATION", "VERITAS_CODE_MODEL"),
        ("math", "VERITAS_MATH_GPU_DEVICE_IDS", "VERITAS_MATH_TENSOR_PARALLEL_SIZE", "VERITAS_MATH_PIPELINE_PARALLEL_SIZE", "VERITAS_MATH_GPU_MEMORY_UTILIZATION", "VERITAS_MATH_MODEL"),
    ];
    let mut errors = Vec::new();
    let mut warnings = Vec::new();
    if gpu_count > 0 && actual_inventory.is_none() {
        let message = "VERITAS_GPU_COUNT is greater than zero, but nvidia-smi is unavailable on this host.".to_string();
        if strict { errors.push(message); } else { warnings.push(format!("{message} Live GPU proof will occur when Docker/vLLM starts.")); }
    }
    if actual_count > 0 && gpu_count > actual_count {
        errors.push(format!("Declared VERITAS_GPU_COUNT={gpu_count} exceeds detected NVIDIA GPU count={actual_count}."));
    }
    for (role, ids_key, tp_key, pp_key, util_key, model_key) in roles {
        let ids_raw = runtime_env_value(&env_text, ids_key).unwrap_or_else(|| "0".to_string());
        let ids = parse_gpu_ids(&ids_raw);
        let tp = runtime_env_value(&env_text, tp_key).unwrap_or_else(|| "1".to_string()).parse::<usize>().unwrap_or(1);
        let pp = runtime_env_value(&env_text, pp_key).unwrap_or_else(|| "1".to_string()).parse::<usize>().unwrap_or(1);
        let util = runtime_env_value(&env_text, util_key).unwrap_or_else(|| "0.60".to_string()).parse::<f64>().unwrap_or(0.60);
        let model = runtime_env_value(&env_text, model_key).unwrap_or_default();
        if gpu_count == 0 {
            if tp > 1 || pp > 1 { errors.push(format!("{role} requests tensor/pipeline parallelism without declared GPUs.")); }
            continue;
        }
        if ids.is_empty() { errors.push(format!("{role} has no GPU IDs configured in {ids_key}.")); }
        if tp == 0 { errors.push(format!("{role} tensor_parallel_size must be >= 1.")); }
        if pp == 0 { errors.push(format!("{role} pipeline_parallel_size must be >= 1.")); }
        if tp > ids.len() { errors.push(format!("{role} tensor_parallel_size={tp} exceeds assigned GPU count {} ({ids_raw}).", ids.len())); }
        if !(0.05..=0.98).contains(&util) { errors.push(format!("{role} GPU memory utilization {util} must be between 0.05 and 0.98.")); }
        for id in &ids {
            if *id >= gpu_count { errors.push(format!("{role} GPU id {id} is outside declared range 0..{}.", gpu_count.saturating_sub(1))); }
            if actual_count > 0 && *id >= actual_count { errors.push(format!("{role} GPU id {id} is outside detected range 0..{}.", actual_count.saturating_sub(1))); }
        }
        if let Some(inventory) = actual_inventory.as_ref() {
            let available_gb = assigned_free_memory_gb(inventory, &ids) * util;
            let hint_gb = model_vram_hint_gb(&model);
            if hint_gb > 0.0 && available_gb > 0.0 && hint_gb > available_gb {
                warnings.push(format!("{role} model {model} may need ~{hint_gb:.1}GB VRAM, but assigned usable free memory is ~{available_gb:.1}GB after utilization={util}. Consider smaller model, quantization, lower max length, tensor parallelism, or remote fallback."));
            }
        }
    }
    if errors.is_empty() {
        println!("✓ GPU/vLLM routing config is structurally valid for declared GPU count {gpu_count}.");
        if actual_count > 0 { println!("✓ Detected {actual_count} NVIDIA GPU(s) through nvidia-smi."); }
        for warning in warnings { println!("⚠ {warning}"); }
        println!("Next proof gate: run `scripts/e2e/live-vllm-smoke.sh` on the GPU host after models are downloaded.");
        Ok(())
    } else {
        for warning in warnings { eprintln!("⚠ {warning}"); }
        for error in &errors { eprintln!("✗ {error}"); }
        Err(anyhow!("GPU/vLLM routing config is invalid; fix `.veritas/runtime.env` or rerun `veritas init`."))
    }
}

fn parse_gpu_ids(value: &str) -> Vec<usize> {
    value.split(',').filter_map(|part| part.trim().parse::<usize>().ok()).collect()
}

fn detect_gpu_inventory() -> Option<Vec<(usize, f64)>> {
    let output = Command::new("nvidia-smi")
        .args(["--query-gpu=index,memory.free", "--format=csv,noheader,nounits"])
        .output()
        .ok()?;
    if !output.status.success() { return None; }
    let text = String::from_utf8_lossy(&output.stdout);
    let mut inventory = Vec::new();
    for line in text.lines() {
        let mut parts = line.split(',');
        let id = parts.next().and_then(|v| v.trim().parse::<usize>().ok());
        let free_mb = parts.next().and_then(|v| v.trim().parse::<f64>().ok());
        if let (Some(id), Some(free_mb)) = (id, free_mb) { inventory.push((id, free_mb / 1024.0)); }
    }
    Some(inventory)
}

fn assigned_free_memory_gb(inventory: &[(usize, f64)], ids: &[usize]) -> f64 {
    ids.iter().filter_map(|id| inventory.iter().find(|(gpu_id, _)| gpu_id == id).map(|(_, free)| *free)).sum()
}

fn model_vram_hint_gb(model: &str) -> f64 {
    let lower = model.to_ascii_lowercase();
    if lower.contains("32b") { 64.0 }
    else if lower.contains("14b") { 32.0 }
    else if lower.contains("7b") { 18.0 }
    else if lower.contains("deepseek-coder-v2-lite") { 32.0 }
    else { 0.0 }
}

fn runtime_env_value(text: &str, key: &str) -> Option<String> {
    text.lines().find_map(|line| line.strip_prefix(&format!("{key}=")).map(|v| v.trim().to_string()))
}

async fn prompt_shell(http: &Client, api_url: &str) -> Result<()> {
    print_logo();
    println!("Interactive Veritas shell. Commands: plan <goal>, run <goal>, math <formula/prompt>, models, ready, exit");
    loop {
        print!("veritas > ");
        io::stdout().flush()?;
        let mut line = String::new();
        io::stdin().read_line(&mut line)?;
        let line = line.trim();
        if line.is_empty() { continue; }
        if matches!(line, "exit" | "quit" | "q") { break; }
        if line == "models" {
            print_response(http.get(format!("{}/models", api_url)).send().await, "api.models").await?;
            continue;
        }
        if line == "ready" {
            print_response(http.get(format!("{}/ready", api_url)).send().await, "api.ready").await?;
            continue;
        }
        if let Some(goal) = line.strip_prefix("plan ") {
            print_response(http.post(format!("{}/plan", api_url)).json(&json!({"goal": goal})).send().await, "api.plan").await?;
            continue;
        }
        if let Some(goal) = line.strip_prefix("run ") {
            print_response(http.post(format!("{}/run", api_url)).json(&json!({"goal": goal, "language": "rust"})).send().await, "api.run").await?;
            continue;
        }
        if let Some(formula) = line.strip_prefix("math ") {
            print_response(http.post(format!("{}/math-to-code", api_url)).json(&json!({"formula_latex": formula, "language": "rust"})).send().await, "api.math_to_code").await?;
            continue;
        }
        println!("Unknown command. Try: plan <goal>, run <goal>, math <formula>, models, ready, exit");
    }
    Ok(())
}

fn run(cmd: &str, args: &[&str]) -> Result<()> {
    println!("$ {} {}", cmd, args.join(" "));
    let status = Command::new(cmd).args(args).status()?;
    if !status.success() {
        return Err(anyhow!("command failed: {} {}", cmd, args.join(" ")));
    }
    Ok(())
}

async fn print_response(result: Result<reqwest::Response, reqwest::Error>, stage: &str) -> Result<()> {
    match result {
        Ok(response) => {
            let status = response.status();
            let text = response.text().await.unwrap_or_default();
            if status.is_success() {
                println!("{}", pretty_json_or_raw(&text));
                Ok(())
            } else {
                eprintln!("Veritas request failed at {stage} with HTTP {}", status);
                eprintln!("{}", pretty_json_or_raw(&text));
                Err(anyhow!("{stage} failed with HTTP {status}"))
            }
        }
        Err(error) => {
            eprintln!("Veritas request failed at {stage}: {error}");
            eprintln!("Remediation: run `veritas start`, `veritas ready`, and inspect Docker Compose logs.");
            Err(error.into())
        }
    }
}

fn pretty_json_or_raw(text: &str) -> String {
    serde_json::from_str::<Value>(text)
        .and_then(|value| serde_json::to_string_pretty(&value))
        .unwrap_or_else(|_| text.to_string())
}
