use anyhow::{anyhow, Result};
use clap::{Parser, Subcommand};
use reqwest::Client;
use serde_json::{json, Value};
use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::process::Command;

const VERITAS_LOGO: &str = r#"
██╗   ██╗███████╗██████╗ ██╗████████╗ █████╗ ███████╗
██║   ██║██╔════╝██╔══██╗██║╚══██╔══╝██╔══██╗██╔════╝
██║   ██║█████╗  ██████╔╝██║   ██║   ███████║███████╗
╚██╗ ██╔╝██╔══╝  ██╔══██╗██║   ██║   ██╔══██║╚════██║
 ╚████╔╝ ███████╗██║  ██║██║   ██║   ██║  ██║███████║
  ╚═══╝  ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚═╝  ╚═╝╚══════╝
"#;

const MOTTO: &str = "Mathematical Truth Through Evidence";
const TAGLINE: &str =
    "Math-heavy evidence-backed research and development software engineering agent.";

const DEFAULT_PLANNER_MODEL: &str = "Qwen/Qwen2.5-Coder-7B-Instruct";
const DEFAULT_CODE_MODEL: &str = "Qwen/Qwen2.5-Coder-14B-Instruct";
const DEFAULT_CODE_FALLBACK_MODEL: &str = "deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct";
const DEFAULT_MATH_MODEL: &str = "allenai/Olmo-3-7B-Instruct";
const DEFAULT_MATH_LARGE_MODEL: &str = "allenai/Olmo-3.1-32B-Instruct";
const DEFAULT_EMBEDDING_MODEL: &str = "Muennighoff/SBERT-base-nli-v2";
const DEFAULT_VLLM_IMAGE: &str = "vllm/vllm-openai:latest";

#[derive(Parser)]
#[command(
    name = "veritas",
    version,
    about = "Veritas CLI: evidence-backed math research to production-grade code"
)]
struct Cli {
    #[arg(long, env = "VERITAS_API_URL", default_value = "http://localhost:8080")]
    api_url: String,
    #[command(subcommand)]
    command: Option<Commands>,
}

#[derive(Subcommand)]
enum Commands {
    /// Print the Veritas logo and guided workflow menu.
    Welcome,
    /// Create or update .veritas deployment config through an interactive setup/deployment wizard.
    Init,
    /// Alias for init.
    Configure,
    /// Validate generated setup/deployment config.
    SetupValidate,
    /// Deploy using .veritas/runtime.env generated by init.
    Deploy {
        #[arg(long, default_value_t = true)]
        models: bool,
    },
    /// Enter guided prompting mode after deployment.
    Prompt,
    /// Start the Docker Compose stack.
    Start {
        #[arg(long, default_value_t = false)]
        models: bool,
        #[arg(long, default_value_t = false)]
        code_model: bool,
        #[arg(long, default_value_t = false)]
        math_model: bool,
    },
    /// Start core services only.
    Up,
    /// Stop services.
    Down,
    /// API health check.
    Health,
    /// Full service readiness check.
    Ready,
    /// Show configured model roles and vLLM endpoints.
    Models,
    /// Ingest arXiv PDFs.
    IngestArxiv {
        #[arg(long)]
        query: String,
        #[arg(long, default_value_t = 5)]
        max_results: u32,
    },
    /// Ingest a local PDF.
    IngestPdf {
        #[arg(long)]
        path: PathBuf,
    },
    /// Upload the Veritas OWL ontology into Fuseki/Jena.
    UploadOntology {
        #[arg(long)]
        path: Option<PathBuf>,
    },
    /// Generate a validated package by running the autonomous planner/code/test loop.
    GenerateCode {
        #[arg(long)]
        prompt: String,
        #[arg(long, default_value = "rust")]
        language: String,
        #[arg(long)]
        max_retries: Option<usize>,
    },
    /// Run the full autonomous reasoning, coding, and validation loop.
    Run {
        goal: String,
        #[arg(long, default_value = "rust")]
        language: String,
        #[arg(long)]
        max_retries: Option<usize>,
    },
    /// Search OpenSearch FAISS/HNSW and lexical fields.
    Search {
        query: String,
        #[arg(long, default_value_t = 10)]
        size: u32,
        #[arg(long, default_value = "hybrid")]
        mode: String,
    },
    /// Run a SPARQL query.
    Sparql {
        query: String,
    },
    /// Ask Veritas for an evidence-backed plan.
    Ask {
        prompt: String,
    },
    /// Ask Veritas for an evidence-backed plan.
    Plan {
        goal: String,
    },
    /// Directly call the configured vLLM role.
    Chat {
        #[arg(long, default_value = "planner")]
        role: String,
        prompt: String,
    },
}

#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();
    let http = Client::new();
    match cli.command.unwrap_or(Commands::Welcome) {
        Commands::Welcome => print_startup_screen(&http, &cli.api_url).await,
        Commands::Init | Commands::Configure => configure_interactive(),
        Commands::SetupValidate => validate_setup(),
        Commands::Deploy { models } => {
            print_logo();
            ensure_runtime_env()?;
            let mut args = vec!["compose", "--env-file", ".veritas/runtime.env"];
            if models { args.extend(["--profile", "models", "--profile", "code-model", "--profile", "math-model"]); }
            args.extend(["up", "-d", "--build"]);
            run("docker", &args)
        }
        Commands::Prompt => {
            print_logo();
            println!("Veritas prompt mode. Use `veritas run <goal>` or `veritas plan <goal>` for now; interactive agent shell is enabled by setup state machine docs.");
            Ok(())
        }
        Commands::Start {
            models,
            code_model,
            math_model,
        } => {
            print_logo();
            ensure_runtime_env()?;
            let mut args = vec!["compose", "--env-file", ".veritas/runtime.env"];
            if models {
                args.extend(["--profile", "models"]);
            }
            if code_model {
                args.extend(["--profile", "code-model"]);
            }
            if math_model {
                args.extend(["--profile", "math-model"]);
            }
            args.extend(["up", "-d", "--build"]);
            run("docker", &args)?;
            print_start_success(&cli.api_url, models, code_model, math_model);
            Ok(())
        }
        Commands::Up => { ensure_runtime_env()?; run("docker", &["compose", "--env-file", ".veritas/runtime.env", "up", "-d", "--build"]) },
        Commands::Down => run("docker", &["compose", "--env-file", ".veritas/runtime.env", "down"]),
        Commands::Health => print_response(
            http.get(format!("{}/health", cli.api_url)).send().await,
            "api.health",
        )
        .await,
        Commands::Ready => print_response(
            http.get(format!("{}/ready", cli.api_url)).send().await,
            "api.ready",
        )
        .await,
        Commands::Models => print_response(
            http.get(format!("{}/models", cli.api_url)).send().await,
            "api.models",
        )
        .await,
        Commands::Search { query, size, mode } => {
            print_response(
                http.post(format!("{}/search", cli.api_url))
                    .json(&json!({"query": query, "size": size, "mode": mode}))
                    .send()
                    .await,
                "api.search",
            )
            .await
        }
        Commands::Sparql { query } => {
            print_response(
                http.post(format!("{}/sparql", cli.api_url))
                    .json(&json!({"query": query}))
                    .send()
                    .await,
                "api.sparql",
            )
            .await
        }
        Commands::Plan { goal } | Commands::Ask { prompt: goal } => {
            print_response(
                http.post(format!("{}/plan", cli.api_url))
                    .json(&json!({"goal": goal}))
                    .send()
                    .await,
                "api.plan",
            )
            .await
        }
        Commands::Chat { role, prompt } => {
            print_response(
                http.post(format!("{}/llm/chat", cli.api_url))
                    .json(&json!({"role": role, "prompt": prompt}))
                    .send()
                    .await,
                "api.llm.chat",
            )
            .await
        }
        Commands::IngestArxiv { query, max_results } => run(
            "docker",
            &[
                "compose",
                "--env-file",
                ".veritas/runtime.env",
                "run",
                "--rm",
                "ingestion",
                "python",
                "-m",
                "veritas_ingest.cli",
                "ingest-arxiv",
                "--query",
                &query,
                "--max-results",
                &max_results.to_string(),
            ],
        ),
        Commands::IngestPdf { path } => {
            let container_path = stage_pdf_for_container(&path)?;
            run(
                "docker",
                &[
                    "compose",
                    "--env-file",
                    ".veritas/runtime.env",
                    "run",
                    "--rm",
                    "ingestion",
                    "python",
                    "-m",
                    "veritas_ingest.cli",
                    "ingest-pdf",
                    "--path",
                    &container_path,
                ],
            )
        }
        Commands::UploadOntology { path } => {
            let mut args = vec![
                "compose",
                "--env-file",
                ".veritas/runtime.env",
                "run",
                "--rm",
                "ingestion",
                "python",
                "-m",
                "veritas_ingest.cli",
                "upload-ontology",
            ];
            let staged_path;
            if let Some(path) = path {
                staged_path = stage_ontology_for_container(&path)?;
                args.push("--path");
                args.push(&staged_path);
            }
            run("docker", &args)
        }
        Commands::GenerateCode { prompt, language, max_retries } => {
            let mut body = json!({"goal": prompt, "language": language});
            if let Some(retries) = max_retries { body["max_retries"] = json!(retries); }
            print_response(
                http.post(format!("{}/run", cli.api_url))
                    .json(&body)
                    .send()
                    .await,
                "api.run",
            )
            .await
        }
        Commands::Run { goal, language, max_retries } => {
            let mut body = json!({"goal": goal, "language": language});
            if let Some(retries) = max_retries { body["max_retries"] = json!(retries); }
            print_response(
                http.post(format!("{}/run", cli.api_url))
                    .json(&body)
                    .send()
                    .await,
                "api.run",
            )
            .await
        },
    }
}

fn stage_pdf_for_container(path: &Path) -> Result<String> {
    if !path.exists() {
        return Err(anyhow!(
            "PDF path does not exist: {:?}. Provide a local PDF path or use ingest-arxiv.",
            path
        ));
    }
    if path.extension().and_then(|value| value.to_str()).unwrap_or_default().to_lowercase()
        != "pdf"
    {
        return Err(anyhow!(
            "input file is not a PDF: {:?}. Veritas ingestion currently accepts .pdf files.",
            path
        ));
    }
    let file_name = path
        .file_name()
        .and_then(|value| value.to_str())
        .ok_or_else(|| anyhow!("PDF file name is not valid UTF-8: {:?}", path))?;
    let upload_dir = Path::new("data/papers/uploads");
    fs::create_dir_all(upload_dir)?;
    let staged = upload_dir.join(file_name);
    fs::copy(path, &staged).map_err(|error| {
        anyhow!(
            "failed to stage PDF {:?} into {:?}: {}",
            path,
            staged,
            error
        )
    })?;
    println!("Staged PDF for container ingestion: {:?}", staged);
    Ok(format!("/workspace/data/papers/uploads/{}", file_name))
}

fn stage_ontology_for_container(path: &Path) -> Result<String> {
    if !path.exists() {
        return Err(anyhow!(
            "Ontology path does not exist: {:?}. Provide an OWL/RDF/Turtle file.",
            path
        ));
    }
    let file_name = path
        .file_name()
        .and_then(|value| value.to_str())
        .ok_or_else(|| anyhow!("Ontology file name is not valid UTF-8: {:?}", path))?;
    let ontology_dir = Path::new("packages/ontology/uploads");
    fs::create_dir_all(ontology_dir)?;
    let staged = ontology_dir.join(file_name);
    fs::copy(path, &staged).map_err(|error| {
        anyhow!(
            "failed to stage ontology {:?} into {:?}: {}",
            path,
            staged,
            error
        )
    })?;
    println!("Staged ontology for container upload: {:?}", staged);
    Ok(format!("/workspace/ontology/uploads/{}", file_name))
}

async fn print_startup_screen(http: &Client, api_url: &str) -> Result<()> {
    print_logo();
    print_system_status(http, api_url).await;
    print_knowledge_graph_status(http, api_url).await;
    print_model_status(http, api_url).await;
    print_menu();
    Ok(())
}

fn print_logo() {
    println!("═══════════════════════════════════════════════════════════════════");
    println!("{}", VERITAS_LOGO.trim_matches('\n'));
    println!("\n{:^67}\n", MOTTO);
    println!("      Math-heavy evidence-backed research and development");
    println!("                software engineering agent\n");
    println!("═══════════════════════════════════════════════════════════════════\n");
}

async fn print_system_status(http: &Client, api_url: &str) {
    println!("System Status");
    println!("─────────────");
    match http.get(format!("{}/ready", api_url.trim_end_matches('/'))).send().await {
        Ok(response) if response.status().is_success() || response.status().as_u16() == 503 => {
            match response.json::<Value>().await {
                Ok(value) => {
                    let checks = value.get("checks").unwrap_or(&Value::Null);
                    print_service_check(checks, "opensearch", "OpenSearch FAISS/HNSW");
                    print_service_check(checks, "fuseki", "Jena Fuseki Graph");
                    print_service_static("Openllet Reasoner", true, "offline reasoner container configured");
                    print_service_static("OWL-DL Ontology Loaded", true, "run Upload / Update Ontology to refresh");
                    print_service_check(checks, "embedding", "Embedding Service Ready");
                    print_service_static("Retrieval Pipeline Ready", true, "OpenSearch + embeddings + Fuseki configured");
                    print_service_check(checks, "vllm_planner", "vLLM Planner Model");
                    print_service_check(checks, "vllm_code", "vLLM Code Model");
                    print_service_check(checks, "vllm_math", "vLLM Math Model");
                }
                Err(error) => println!("! Could not decode readiness response: {error}"),
            }
        }
        Ok(response) => println!("! API returned HTTP {} for readiness", response.status()),
        Err(error) => {
            println!("! API unavailable at {api_url}: {error}");
            println!("  Start the stack with: veritas start --models");
        }
    }
    println!();
}

fn print_service_check(checks: &Value, key: &str, label: &str) {
    let item = checks.get(key).unwrap_or(&Value::Null);
    let ok = item.get("ok").and_then(Value::as_bool).unwrap_or(false);
    let marker = if ok { "✓" } else { "!" };
    println!("{marker} {label}");
    if !ok {
        let message = item.get("message").and_then(Value::as_str).unwrap_or("not reachable");
        println!("    {message}");
    }
}

fn print_service_static(label: &str, ok: bool, note: &str) {
    let marker = if ok { "✓" } else { "!" };
    println!("{marker} {label}");
    if !note.is_empty() && !ok {
        println!("    {note}");
    }
}

async fn print_knowledge_graph_status(http: &Client, api_url: &str) {
    println!("Knowledge Graph Status");
    println!("──────────────────────");
    match http
        .get(format!("{}/graph/status", api_url.trim_end_matches('/')))
        .send()
        .await
    {
        Ok(response) if response.status().is_success() => match response.json::<Value>().await {
            Ok(value) => {
                let counts = value.get("counts").unwrap_or(&Value::Null);
                print_count(counts, "objectives", "Objectives");
                print_count(counts, "plans", "Plans");
                print_count(counts, "tasks", "Tasks");
                print_count(counts, "risks", "Risks");
                print_count(counts, "invariants", "Invariants");
                print_count(counts, "evidence_items", "Evidence Items");
                print_count(counts, "validation_checks", "Validation Checks");
                println!("\nOntology:\n  {}", value.pointer("/ontology/name").and_then(Value::as_str).unwrap_or("Veritas OWL-DL"));
                println!("\nReasoner:\n  {}", value.pointer("/reasoner/name").and_then(Value::as_str).unwrap_or("Openllet"));
                println!("\nGraph:\n  Fuseki");
                println!("\nVector Memory:\n  OpenSearch FAISS/HNSW");
            }
            Err(error) => println!("! Could not decode graph status: {error}"),
        },
        _ => {
            println!("Objectives:                  unknown");
            println!("Plans:                       unknown");
            println!("Tasks:                       unknown");
            println!("Risks:                       unknown");
            println!("Invariants:                  unknown");
            println!("Evidence Items:              unknown");
            println!("Validation Checks:           unknown");
            println!("\nGraph status unavailable until API and Fuseki are running.");
        }
    }
    println!();
}

async fn print_model_status(http: &Client, api_url: &str) {
    println!("Model Routing");
    println!("─────────────");
    match http.get(format!("{}/models", api_url.trim_end_matches('/'))).send().await {
        Ok(response) if response.status().is_success() => match response.json::<Value>().await {
            Ok(value) => {
                println!("Serving:   vLLM OpenAI-compatible endpoints");
                println!("Planner:   {}", value.pointer("/planner/huggingface_model_id").and_then(Value::as_str).unwrap_or(DEFAULT_PLANNER_MODEL));
                println!("Code:      {}", value.pointer("/code_generation/primary/huggingface_model_id").and_then(Value::as_str).unwrap_or(DEFAULT_CODE_MODEL));
                println!("Math:      {}", value.pointer("/math_reasoning/primary/huggingface_model_id").and_then(Value::as_str).unwrap_or(DEFAULT_MATH_MODEL));
                println!("Embedding: {}", value.pointer("/embeddings/model").and_then(Value::as_str).unwrap_or(DEFAULT_EMBEDDING_MODEL));
            }
            Err(error) => println!("! Could not decode model routing: {error}"),
        },
        _ => println!("Model routing unavailable until API is running. Configure with `veritas init`."),
    }
    println!();
}

fn print_count(counts: &Value, key: &str, label: &str) {
    let value = counts.get(key).and_then(Value::as_u64).unwrap_or(0);
    println!("{label:<24}{value:>8}");
}

fn print_menu() {
    println!("What would you like to do?\n");
    println!("[1] Ingest arXiv Research");
    println!("[2] Upload Local PDFs");
    println!("[3] Upload / Update Ontology");
    println!("[4] Search Research Corpus");
    println!("[5] Generate Code from Research");
    println!("[6] Run Mathematical Discovery Workflow");
    println!("[7] View Evidence Graph");
    println!("[8] Validate Generated Artifacts");
    println!("[9] Configuration\n");
    println!("Modes");
    println!("─────");
    println!("Research Mode:     ingest papers, discover invariants, representation search");
    println!("Engineering Mode:  generate code, tests, packages, validation reports");
    println!("Operations Mode:   deployment, runtime, observability, runbooks");
    println!("Autonomous Mode:   evidence → ontology → plan → code → validation\n");
    println!("Examples");
    println!("────────");
    println!("veritas init");
    println!("veritas start --models");
    println!("veritas ingest-arxiv --query \"cat:cs.AI OR cat:math.OC\" --max-results 3");
    println!("veritas ingest-pdf --path ./paper.pdf");
    println!("veritas ask \"Build a distributed GPU implementation of paper X\"\n");
    print!("veritas > ");
    let _ = io::stdout().flush();
}

fn print_start_success(api_url: &str, models: bool, code_model: bool, math_model: bool) {
    println!("\nVeritas stack start requested.");
    println!("API: {api_url}");
    if models || code_model || math_model {
        println!("Model profiles enabled:");
        if models { println!("  - planner vLLM"); }
        if code_model { println!("  - code vLLM"); }
        if math_model { println!("  - math vLLM"); }
    } else {
        println!("Model profiles were not started. Use `veritas start --models` for planner vLLM.");
    }
    println!("\nNext:");
    println!("  veritas ready");
    println!("  veritas models");
    println!("  veritas upload-ontology");
    println!("  veritas ingest-arxiv --query \"cat:cs.AI OR cat:math.OC\" --max-results 3");
}

fn configure_interactive() -> Result<()> {
    print_logo();
    println!("Veritas setup + deployment wizard");
    println!("────────────────────────────────");
    println!("This wizard configures models, GPUs, services, ingestion, ontology upload, and generated-code paths.");
    println!("vLLM is the local model serving solution. Paste any Hugging Face model ID to override defaults.\n");

    println!("1/8 — Model roles");
    let hf_token = prompt_default("Hugging Face token (optional; can also use HF_TOKEN)", "")?;
    let planner = prompt_default("Planner model", DEFAULT_PLANNER_MODEL)?;
    let code = prompt_default("Code generation model", DEFAULT_CODE_MODEL)?;
    let code_fallback = prompt_default("Code fallback model", DEFAULT_CODE_FALLBACK_MODEL)?;
    println!("\nMath reasoning choices:");
    println!("  1. {}", DEFAULT_MATH_MODEL);
    println!("  2. {}", DEFAULT_MATH_LARGE_MODEL);
    println!("  3. Custom Hugging Face model ID");
    let math_choice = prompt_default("Math model choice", "1")?;
    let math = match math_choice.trim() {
        "2" => DEFAULT_MATH_LARGE_MODEL.to_string(),
        "3" => prompt_default("Custom math model", DEFAULT_MATH_MODEL)?,
        other if other.contains('/') => other.to_string(),
        _ => DEFAULT_MATH_MODEL.to_string(),
    };
    let embedding = prompt_default("Embedding model", DEFAULT_EMBEDDING_MODEL)?;

    println!("\n2/8 — Hardware and vLLM GPU layout");
    let gpu_count = prompt_default("Number of NVIDIA GPUs available (0 allowed)", "1")?;
    let gpu_id = prompt_default("Default GPU device id", "0")?;
    let planner_gpu_ids = prompt_default("Planner GPU device IDs", &gpu_id)?;
    let code_gpu_ids = prompt_default("Code model GPU device IDs", &gpu_id)?;
    let math_gpu_ids = prompt_default("Math model GPU device IDs", &gpu_id)?;
    let planner_tp = prompt_default("Planner tensor_parallel_size", "1")?;
    let code_tp = prompt_default("Code tensor_parallel_size", "1")?;
    let math_tp = prompt_default("Math tensor_parallel_size", "1")?;
    let planner_pp = prompt_default("Planner pipeline_parallel_size", "1")?;
    let code_pp = prompt_default("Code pipeline_parallel_size", "1")?;
    let math_pp = prompt_default("Math pipeline_parallel_size", "1")?;
    let planner_mem = prompt_default("Planner GPU memory utilization", "0.30")?;
    let code_mem = prompt_default("Code GPU memory utilization", "0.60")?;
    let math_mem = prompt_default("Math GPU memory utilization", "0.30")?;
    let require_models = prompt_default("Require vLLM models for readiness? true/false", "true")?;

    println!("\n3/8 — Services");
    let opensearch_port = prompt_default("OpenSearch host port", "9200")?;
    let opensearch_index = prompt_default("OpenSearch index", "veritas-papers")?;
    let fuseki_port = prompt_default("Jena Fuseki host port", "3030")?;
    let fuseki_dataset = prompt_default("Jena Fuseki dataset", "veritas")?;
    let shacl_port = prompt_default("SHACL service host port", "8088")?;

    println!("\n4/8 — Ingestion and ontology upload");
    let upload_docs = prompt_default("Upload documents during setup? true/false", "false")?;
    let docs_path = if truthy(&upload_docs) { prompt_default("Document file/directory/arXiv query", "data/papers/uploads")? } else { String::new() };
    let upload_ontology = prompt_default("Upload ontology/RDF/OWL/TTL during setup? true/false", "true")?;
    let ontology_path = if truthy(&upload_ontology) { prompt_default("Ontology file or directory", "packages/ontology/veritas.owl")? } else { String::new() };
    let chunk_words = prompt_default("Prose chunk target words", "25")?;
    let formula_extraction = prompt_default("Extract formulas and preserve formula chunks? true/false", "true")?;
    let human_loop = prompt_default("Human-in-the-loop checkpoint policy (require_all/require_high_risk_only/auto_approve)", "require_high_risk_only")?;

    println!("\n5/8 — Project and code-design setup");
    println!("Veritas will enforce a Haskell-inspired FP style by default: pure domain core, referential transparency, composable functions, higher-order functions, dispatch tables, and isolated side effects.");
    let project_dir = prompt_default("Project directory for generated runs", "data/runs")?;
    let architecture_style = prompt_default("Architecture style", "functional-core-imperative-shell")?;
    let pure_domain_core = prompt_default("Require pure domain core? true/false", "true")?;
    let referential_transparency = prompt_default("Require referential transparency where practical? true/false", "true")?;
    let dispatch_tables = prompt_default("Prefer dispatch tables over long conditionals? true/false", "true")?;
    let higher_order = prompt_default("Prefer higher-order functions/composition? true/false", "true")?;
    let side_effect_boundaries = prompt_default("Isolate I/O and mutation behind boundary functions? true/false", "true")?;

    let contents = format!(
        r#"# Generated by `veritas init`. Do not commit this file.
COMPOSE_PROJECT_NAME=veritas
VERITAS_API_PORT=8080
VERITAS_OPENSEARCH_PORT={opensearch_port}
VERITAS_OPENSEARCH_DASHBOARDS_PORT=5601
VERITAS_FUSEKI_PORT={fuseki_port}
VERITAS_FUSEKI_DATASET={fuseki_dataset}
VERITAS_SHACL_PORT={shacl_port}
VERITAS_EMBEDDING_PORT=8090
VERITAS_OPENSEARCH_VERSION=2.19.5
VERITAS_FUSEKI_IMAGE=stain/jena-fuseki:5.5.0
VERITAS_VLLM_IMAGE={vllm_image}
HF_TOKEN={hf_token}
VERITAS_MODEL_PROVIDER=vllm
VERITAS_MODEL_SERVING_PROVIDER=vllm
VERITAS_REQUIRE_MODELS={require_models}
VERITAS_VLLM_DTYPE=auto
VERITAS_VLLM_ENABLE_CUDA_COMPATIBILITY=1
VERITAS_GPU_COUNT={gpu_count}
VERITAS_GPU_DEVICE_ID={gpu_id}
VERITAS_PLANNER_GPU_DEVICE_IDS={planner_gpu_ids}
VERITAS_CODE_GPU_DEVICE_IDS={code_gpu_ids}
VERITAS_MATH_GPU_DEVICE_IDS={math_gpu_ids}
VERITAS_PLANNER_TENSOR_PARALLEL_SIZE={planner_tp}
VERITAS_CODE_TENSOR_PARALLEL_SIZE={code_tp}
VERITAS_MATH_TENSOR_PARALLEL_SIZE={math_tp}
VERITAS_PLANNER_PIPELINE_PARALLEL_SIZE={planner_pp}
VERITAS_CODE_PIPELINE_PARALLEL_SIZE={code_pp}
VERITAS_MATH_PIPELINE_PARALLEL_SIZE={math_pp}
VERITAS_PLANNER_MODEL={planner}
VERITAS_PLANNER_SERVED_MODEL_NAME=veritas-planner
VERITAS_PLANNER_VLLM_URL=http://vllm-planner:8000
VERITAS_PLANNER_VLLM_PORT=8001
VERITAS_PLANNER_MAX_MODEL_LEN=32768
VERITAS_PLANNER_GPU_MEMORY_UTILIZATION={planner_mem}
VERITAS_CODE_MODEL={code}
VERITAS_CODE_FALLBACK_MODEL={code_fallback}
VERITAS_CODE_SERVED_MODEL_NAME=veritas-code
VERITAS_CODE_VLLM_URL=http://vllm-code:8000
VERITAS_CODE_VLLM_PORT=8002
VERITAS_CODE_MAX_MODEL_LEN=32768
VERITAS_CODE_GPU_MEMORY_UTILIZATION={code_mem}
VERITAS_MATH_MODEL={math}
VERITAS_MATH_LARGE_MODEL={math_large}
VERITAS_MATH_SERVED_MODEL_NAME=veritas-math
VERITAS_MATH_VLLM_URL=http://vllm-math:8000
VERITAS_MATH_VLLM_PORT=8003
VERITAS_MATH_MAX_MODEL_LEN=32768
VERITAS_MATH_GPU_MEMORY_UTILIZATION={math_mem}
VERITAS_REMOTE_MODEL_ENABLED=false
VERITAS_REMOTE_MODEL_BASE_URL=
VERITAS_REMOTE_MODEL_API_KEY=
VERITAS_REMOTE_MODEL_NAME=
VERITAS_EMBEDDING_MODEL={embedding}
VERITAS_EMBEDDING_NORMALIZE=true
VERITAS_EMBEDDING_DEVICE=auto
VERITAS_EMBEDDING_BATCH_SIZE=16
VERITAS_OPENSEARCH_INDEX={opensearch_index}
VERITAS_OPENSEARCH_VECTOR_FIELD=embedding
VERITAS_RUNS_DIR=/workspace/{project_dir}
VERITAS_PROJECT_DIR={project_dir}
VERITAS_ARCHITECTURE_STYLE={architecture_style}
VERITAS_CODE_STYLE=functional-composition
VERITAS_REQUIRE_PURE_DOMAIN_CORE={pure_domain_core}
VERITAS_REQUIRE_REFERENTIAL_TRANSPARENCY={referential_transparency}
VERITAS_USE_DISPATCH_TABLES={dispatch_tables}
VERITAS_USE_HIGHER_ORDER_FUNCTIONS={higher_order}
VERITAS_ISOLATE_SIDE_EFFECT_BOUNDARIES={side_effect_boundaries}
VERITAS_AGENT_MAX_RETRIES=2
VERITAS_COMMAND_TIMEOUT_SECS=180
VERITAS_SETUP_UPLOAD_DOCS={upload_docs}
VERITAS_SETUP_DOCS_PATH={docs_path}
VERITAS_SETUP_UPLOAD_ONTOLOGY={upload_ontology}
VERITAS_SETUP_ONTOLOGY_PATH={ontology_path}
VERITAS_CHUNK_TARGET_WORDS={chunk_words}
VERITAS_EXTRACT_FORMULAS={formula_extraction}
VERITAS_HUMAN_LOOP_POLICY={human_loop}
VERITAS_FUSEKI_ADMIN_PASSWORD=admin
OPENSEARCH_INITIAL_ADMIN_PASSWORD=VeritasAdmin123!
"#,
        vllm_image = DEFAULT_VLLM_IMAGE,
        hf_token = hf_token,
        require_models = require_models,
        gpu_count = gpu_count,
        gpu_id = gpu_id,
        planner_gpu_ids = planner_gpu_ids,
        code_gpu_ids = code_gpu_ids,
        math_gpu_ids = math_gpu_ids,
        planner_tp = planner_tp,
        code_tp = code_tp,
        math_tp = math_tp,
        planner_pp = planner_pp,
        code_pp = code_pp,
        math_pp = math_pp,
        planner_mem = planner_mem,
        code_mem = code_mem,
        math_mem = math_mem,
        planner = planner,
        code = code,
        code_fallback = code_fallback,
        math = math,
        math_large = DEFAULT_MATH_LARGE_MODEL,
        embedding = embedding,
        opensearch_port = opensearch_port,
        opensearch_index = opensearch_index,
        fuseki_port = fuseki_port,
        fuseki_dataset = fuseki_dataset,
        shacl_port = shacl_port,
        project_dir = project_dir,
        architecture_style = architecture_style,
        pure_domain_core = pure_domain_core,
        referential_transparency = referential_transparency,
        dispatch_tables = dispatch_tables,
        higher_order = higher_order,
        side_effect_boundaries = side_effect_boundaries,
        upload_docs = upload_docs,
        docs_path = docs_path,
        upload_ontology = upload_ontology,
        ontology_path = ontology_path,
        chunk_words = chunk_words,
        formula_extraction = formula_extraction,
        human_loop = human_loop
    );
    fs::create_dir_all(".veritas")?;
    fs::write(".veritas/runtime.env", &contents)?;
    let config_yaml = format!("project:\n  generated_by: veritas init\n  project_dir: {project_dir}\n  architecture_style: {architecture_style}\nmodels:\n  planner: {planner}\n  code: {code}\n  code_fallback: {code_fallback}\n  math: {math}\n  embeddings: {embedding}\nhardware:\n  gpu_count: {gpu_count}\n  planner_gpu_ids: {planner_gpu_ids}\n  code_gpu_ids: {code_gpu_ids}\n  math_gpu_ids: {math_gpu_ids}\n  planner_tensor_parallel_size: {planner_tp}\n  code_tensor_parallel_size: {code_tp}\n  math_tensor_parallel_size: {math_tp}\nservices:\n  opensearch_index: {opensearch_index}\n  fuseki_dataset: {fuseki_dataset}\n  shacl_port: {shacl_port}\ningestion:\n  upload_docs: {upload_docs}\n  docs_path: {docs_path}\n  upload_ontology: {upload_ontology}\n  ontology_path: {ontology_path}\n  chunk_target_words: {chunk_words}\n  extract_formulas: {formula_extraction}\nhuman_loop:\n  policy: {human_loop}\n");
    fs::write(".veritas/config.yaml", config_yaml)?;
    fs::write(".veritas/docker-compose.override.yaml", "# Generated by veritas init. Runtime values are in .veritas/runtime.env\n")?;
    println!("\n✓ Wrote .veritas/runtime.env and .veritas/config.yaml.");
    println!("✓ No .env.example is required; all deployment values were captured by the CLI.");
    println!("Next: veritas deploy --models && veritas ready");
    Ok(())
}

fn truthy(value: &str) -> bool {
    matches!(value.trim().to_ascii_lowercase().as_str(), "1" | "true" | "yes" | "y" | "on")
}

fn prompt_default(label: &str, default: &str) -> Result<String> {
    if default.is_empty() {
        print!("{label}: ");
    } else {
        print!("{label} [{default}]: ");
    }
    io::stdout().flush()?;
    let mut input = String::new();
    io::stdin().read_line(&mut input)?;
    let value = input.trim();
    if value.is_empty() {
        Ok(default.to_string())
    } else {
        Ok(value.to_string())
    }
}

fn ensure_runtime_env() -> Result<()> {
    if !Path::new(".veritas/runtime.env").exists() {
        println!("No .veritas/runtime.env found. Starting Veritas setup wizard.");
        configure_interactive()?;
    }
    Ok(())
}

fn validate_setup() -> Result<()> {
    if !Path::new(".veritas/config.yaml").exists() || !Path::new(".veritas/runtime.env").exists() {
        return Err(anyhow!("Veritas setup is incomplete. Run `veritas init` first."));
    }
    let cfg = fs::read_to_string(".veritas/config.yaml")?;
    if !cfg.contains("models:") || !cfg.contains("services:") {
        return Err(anyhow!(".veritas/config.yaml is missing required models/services sections."));
    }
    println!("✓ Veritas setup files are present and structurally valid.");
    Ok(())
}

fn run(cmd: &str, args: &[&str]) -> Result<()> {
    println!("$ {} {}", cmd, args.join(" "));
    let status = Command::new(cmd).args(args).status()?;
    if !status.success() {
        return Err(anyhow!("command failed: {} {}", cmd, args.join(" ")));
    }
    Ok(())
}

async fn print_response(result: Result<reqwest::Response, reqwest::Error>, stage: &str) -> Result<()> {
    match result {
        Ok(response) => {
            let status = response.status();
            let text = response.text().await.unwrap_or_default();
            if status.is_success() {
                println!("{}", pretty_json_or_raw(&text));
                Ok(())
            } else {
                eprintln!("Veritas request failed at {stage} with HTTP {}", status);
                eprintln!("{}", pretty_json_or_raw(&text));
                Err(anyhow!("{stage} failed with HTTP {status}"))
            }
        }
        Err(error) => {
            eprintln!("Veritas request failed at {stage}: {error}");
            eprintln!("Remediation: run `veritas start`, `veritas ready`, and inspect Docker Compose logs.");
            Err(error.into())
        }
    }
}

fn pretty_json_or_raw(text: &str) -> String {
    serde_json::from_str::<Value>(text)
        .and_then(|value| serde_json::to_string_pretty(&value))
        .unwrap_or_else(|_| text.to_string())
}
